package video

func extraCanvasSkills(cover func(int) string) []canvasSkillDef {
	return []canvasSkillDef{
		{ID: "drama-cold-open", Name: "冷开场三镜", Tag: "drama", Cover: cover(3), Likes: 540, Added: 980,
			Desc: "用三个可见动作开场，不靠旁白解释设定。",
			Body: skillMD("冷开场三镜",
				"第一集或预告需要立刻抓住人时使用。",
				"1. 镜一：一个反常动作。\n2. 镜二：动作的代价或目击者。\n3. 镜三：把人物推入本集目标。",
				"三镜表：画面、时长、不解释的信息。",
				"不要用字幕说明书世界观。")},
		{ID: "drama-fight-coverage", Name: "动作戏可剪覆盖", Tag: "drama", Cover: cover(17), Likes: 410, Added: 760,
			Desc: "把打戏拆成可读的地理、击打和反应，而不是连续炫技。",
			Body: skillMD("动作戏可剪覆盖",
				"追逐、推搡、短打需要可剪时使用。",
				"1. 先锁空间：门、桌、台阶。\n2. 每次接触写清左右手。\n3. 插入反应与道具。\n4. 高潮只留一个决定性动作。",
				"动作覆盖表。",
				"不要无地理关系的环绕镜头。")},
		{ID: "drama-night-interior", Name: "夜戏室内布光", Tag: "drama", Cover: cover(9), Likes: 360, Added: 670,
			Desc: "给夜戏规定实用光源，避免全黑或无来源霓虹。",
			Body: skillMD("夜戏室内布光",
				"室内夜戏发灰、发黑或假霓虹时使用。",
				"1. 主光必须有灯具。\n2. 窗外只做轮廓。\n3. 肤色保持可读。\n4. 强调色给一个道具。",
				"布光提示词。",
				"不要同时开满所有彩灯。")},
		{ID: "drama-costume-bible", Name: "衣橱连贯表", Tag: "drama", Cover: cover(10), Likes: 320, Added: 590,
			Desc: "按集数锁定服装编号、磨损和换装动机。",
			Body: skillMD("衣橱连贯表",
				"多集换装或角色被说换脸时使用。",
				"1. 每套编号。\n2. 写磨损。\n3. 换装必须有场次理由。\n4. 标志配饰不丢。",
				"衣橱表。",
				"不要每集全新造型。")},
		{ID: "drama-music-cue", Name: "配乐进出点", Tag: "drama", Cover: cover(11), Likes: 280, Added: 510,
			Desc: "规定音乐进入、退出和静默，服务转折而不是垫底。",
			Body: skillMD("配乐进出点",
				"全片都有 BGM 或高潮没有静默时使用。",
				"1. 只在情绪需要时进入。\n2. 对白段落优先干声。\n3. 反转前后各留一拍静默。",
				"音乐轴。",
				"不要全程同一首情绪垫乐。")},
		{ID: "drama-recap", Name: "上集回顾十秒", Tag: "drama", Cover: cover(12), Likes: 300, Added: 560,
			Desc: "用三个旧镜头加一个新钩子做回顾，不剧透本集。",
			Body: skillMD("上集回顾十秒",
				"连载第二集之后使用。",
				"1. 人物关系 3 秒。\n2. 未解决物件 4 秒。\n3. 新集钩子 3 秒。",
				"回顾时间轴。",
				"不要总结主题；不要剧透本集。")},
		{ID: "drama-vfx-brief", Name: "特效镜头简报", Tag: "drama", Cover: cover(13), Likes: 250, Added: 470,
			Desc: "把超自然或科幻效果写成可生成的物理证据。",
			Body: skillMD("特效镜头简报",
				"记忆删除、法术、全息需要可见证据时使用。",
				"1. 效果的物理痕迹。\n2. 持续时长。\n3. 代价必须可见。\n4. 禁用无来源发光。",
				"VFX 简报。",
				"不要用镜头光晕代替规则。")},
		{ID: "drama-extra-casting", Name: "群演与路人规则", Tag: "drama", Cover: cover(14), Likes: 210, Added: 390,
			Desc: "背景人物的密度、服饰年代和禁止抢戏。",
			Body: skillMD("群演与路人规则",
				"街景、食堂、诊所候诊容易穿帮时使用。",
				"1. 密度。\n2. 服装年代。\n3. 路人不看镜头。\n4. 禁止现代潮牌。",
				"群演规范。",
				"不要让路人比主角更精致。")},
		{ID: "drama-location-scout", Name: "勘景清单", Tag: "drama", Cover: cover(15), Likes: 240, Added: 450,
			Desc: "把地点拆成可拍角度、声源和限制。",
			Body: skillMD("勘景清单",
				"选定主场景或过场之前使用。",
				"1. 四个可拍方向。\n2. 实用光源。\n3. 噪声来源。\n4. 角色如何进出。",
				"勘景卡。",
				"不要只写氛围形容词。")},
		{ID: "drama-insert-cutaway", Name: "插入镜头设计", Tag: "drama", Cover: cover(16), Likes: 270, Added: 500,
			Desc: "给对话戏准备手、物件、窗外的呼吸镜头。",
			Body: skillMD("插入镜头设计",
				"对手戏太满、剪辑没有气口时使用。",
				"1. 手部。\n2. 信物状态。\n3. 环境证据。\n4. 每条注明秒数。",
				"插入清单。",
				"不要插入与这场戏无关的空镜。")},
		{ID: "drama-montage", Name: "时间蒙太奇", Tag: "drama", Cover: cover(18), Likes: 330, Added: 610,
			Desc: "用物件状态和光线变化压缩时间，而不是日历翻页。",
			Body: skillMD("时间蒙太奇",
				"需要跳过几天或几个季节时使用。",
				"1. 选一个会变的物件。\n2. 光线或天气递进。\n3. 人物状态微变。",
				"蒙太奇三到五镜。",
				"不要用时钟特写当唯一手法。")},
		{ID: "ecom-unboxing", Name: "开箱五拍", Tag: "ecommerce", Cover: cover(4), Likes: 620, Added: 1140,
			Desc: "开箱节奏：外包装、开合、手感、细节、使用。",
			Body: skillMD("开箱五拍",
				"需要开箱、拆封或材质种草时使用。",
				"1. 外包装 2 秒。\n2. 开启动作。\n3. 手部触感。\n4. 一个细节特写。\n5. 立刻进入使用。",
				"五拍分镜。",
				"不要假装拆了十分钟。")},
		{ID: "ecom-asmr-product", Name: "产品触感镜头", Tag: "ecommerce", Cover: cover(5), Likes: 390, Added: 720,
			Desc: "用声音和手部证明材质，不靠形容词。",
			Body: skillMD("产品触感镜头",
				"织物、包装、气泡水、金属需要质感时使用。",
				"1. 近景手部。\n2. 可听见的材质声。\n3. 光线服务纹理。",
				"触感提示词。",
				"不要过度磨皮让材质消失。")},
		{ID: "ecom-ingredient", Name: "成分故事三镜", Tag: "ecommerce", Cover: cover(6), Likes: 340, Added: 630,
			Desc: "把成分写成可见来源、处理和结果，不编造功效。",
			Body: skillMD("成分故事三镜",
				"食品、个护需要讲来源时使用。",
				"1. 来源场景。\n2. 处理过程。\n3. 回到使用。",
				"三镜 + 口播要点。",
				"不要宣称医疗功效。")},
		{ID: "ecom-seasonal", Name: "季节战役脚本", Tag: "ecommerce", Cover: cover(7), Likes: 310, Added: 580,
			Desc: "节日或换季时只换场景证据，不换品牌气质。",
			Body: skillMD("季节战役脚本",
				"春节、开学、入冬等节点使用。",
				"1. 保留品牌色板。\n2. 换一个季节证据。\n3. 主张仍是原卖点。",
				"战役一页纸。",
				"不要为节日另起一套画风。")},
		{ID: "ecom-objection", Name: "价格异议口播", Tag: "ecommerce", Cover: cover(8), Likes: 280, Added: 520,
			Desc: "先承认顾虑，再给可感知价值，不贬低竞品。",
			Body: skillMD("价格异议口播",
				"评论区问贵、或需要解释规格时使用。",
				"1. 复述顾虑。\n2. 一个可见对比（用量/寿命/场景）。\n3. 回到使用。",
				"30 秒口播。",
				"不要攻击竞品商标。")},
		{ID: "ecom-bundle", Name: "组合装叙事", Tag: "ecommerce", Cover: cover(9), Likes: 250, Added: 470,
			Desc: "把套装写成一次完整使用路径。",
			Body: skillMD("组合装叙事",
				"多 SKU 套装或买赠时使用。",
				"1. 使用顺序。\n2. 每件只给一个职责。\n3. 结尾落在完整场景。",
				"套装分镜。",
				"不要同时介绍十个卖点。")},
		{ID: "ecom-before-after", Name: "前后对比诚实拍", Tag: "ecommerce", Cover: cover(10), Likes: 360, Added: 670,
			Desc: "同一机位、同一光线做前后对比。",
			Body: skillMD("前后对比诚实拍",
				"清洁、收纳、妆造前后需要时使用。",
				"1. 锁机位。\n2. 只改变被测对象。\n3. 时间诚实标注给后期，不让模型写字。",
				"对比分镜。",
				"不要伪造结果。")},
		{ID: "ecom-live-3min", Name: "三分钟直播钩子", Tag: "ecommerce", Cover: cover(11), Likes: 290, Added: 540,
			Desc: "把直播前三分钟写成可切片的结构。",
			Body: skillMD("三分钟直播钩子",
				"模拟直播或切直播切片时使用。",
				"1. 问候与在场证明。\n2. 一个正在发生的使用。\n3. 一个可跟的行动。",
				"三分钟提纲。",
				"不要开场读规格书。")},
		{ID: "ecom-review-harvest", Name: "评价转镜头", Tag: "ecommerce", Cover: cover(12), Likes: 230, Added: 430,
			Desc: "把真实使用反馈改写成可拍的场景，不捏造评价。",
			Body: skillMD("评价转镜头",
				"有用户原话或需要种草转视频时使用。",
				"1. 选一句可拍的原话。\n2. 还原使用场景。\n3. 不添加未发生的效果。",
				"评价镜头脚本。",
				"不要虚构用户身份。")},
		{ID: "ecom-shelf-hero", Name: "货架主图运动", Tag: "ecommerce", Cover: cover(13), Likes: 270, Added: 500,
			Desc: "电商主图的微运动：旋转、手入画、环境反光。",
			Body: skillMD("货架主图运动",
				"主图视频或 360 展示时使用。",
				"1. 主体居中。\n2. 一次运动只做一件事。\n3. 背景克制。",
				"3 条微运动提示词。",
				"不要转盘炫技遮住商品。")},
		{ID: "creative-camera-moves", Name: "运镜词典", Tag: "creative", Cover: cover(14), Likes: 480, Added: 890,
			Desc: "把情绪翻译成推、拉、摇、跟、升，而不是“电影感”。",
			Body: skillMD("运镜词典",
				"提示词只会写电影感时使用。",
				"1. 问要靠近、发现还是逃离。\n2. 选一种运镜。\n3. 写速度。",
				"运镜改写。",
				"不要一镜里堆五种运动。")},
		{ID: "creative-texture-board", Name: "材质板", Tag: "creative", Cover: cover(15), Likes: 350, Added: 640,
			Desc: "墙、地面、织物、金属分开写，避免塑料感。",
			Body: skillMD("材质板",
				"画面发假、发塑料时使用。",
				"1. 四种表面。\n2. 磨损。\n3. 光线如何刮过。",
				"材质提示词。",
				"不要用“8k 超清”代替材质。")},
		{ID: "creative-aging", Name: "做旧与使用痕迹", Tag: "creative", Cover: cover(16), Likes: 260, Added: 480,
			Desc: "给道具和服装写使用痕迹，让世界像被住过。",
			Body: skillMD("做旧与使用痕迹",
				"场景像样板间时使用。",
				"1. 谁用过。\n2. 哪里磨。\n3. 哪里脏得合理。",
				"做旧清单。",
				"不要均匀撒脏。")},
		{ID: "creative-negative-space", Name: "留白与字幕安全区", Tag: "creative", Cover: cover(17), Likes: 240, Added: 450,
			Desc: "为标题和字幕留出空白，并禁止模型写字。",
			Body: skillMD("留白与字幕安全区",
				"后期要叠标题或花字时使用。",
				"1. 主体偏一侧。\n2. 天空或墙面留空。\n3. 明确无文字。",
				"构图提示词。",
				"不要让模型渲染可读书名。")},
		{ID: "creative-color-no-lut", Name: "不靠滤镜的色彩", Tag: "creative", Cover: cover(18), Likes: 310, Added: 570,
			Desc: "用光源色温和物体固有色控制画面，不点名 LUT。",
			Body: skillMD("不靠滤镜的色彩",
				"用户点名某滤镜或青橙默认时使用。",
				"1. 光源色温。\n2. 物体固有色。\n3. 一种强调色。",
				"色彩提示词。",
				"不要写滤镜产品名。")},
		{ID: "creative-parallax", Name: "2.5D 分层", Tag: "creative", Cover: cover(0), Likes: 220, Added: 410,
			Desc: "前景、中景、背景分开写，方便轻微视差。",
			Body: skillMD("2.5D 分层",
				"需要轻微运动的静帧或绘本时使用。",
				"1. 前景遮挡。\n2. 主体中景。\n3. 可移动背景。",
				"分层说明。",
				"不要三层都同等清晰抢戏。")},
		{ID: "creative-stopmo-timing", Name: "定格时序", Tag: "creative", Cover: cover(12), Likes: 200, Added: 380,
			Desc: "给黏土或定格规定步进、抖动和材质。",
			Body: skillMD("定格时序",
				"定格、黏土或手作质感时使用。",
				"1. 可见指纹或工具痕。\n2. 步进感。\n3. 光源稳定。",
				"定格提示词。",
				"不要把它写成平滑 CG。")},
		{ID: "creative-collage", Name: "拼贴叙事板", Tag: "creative", Cover: cover(1), Likes: 190, Added: 360,
			Desc: "把参考拆成可拼的图层职责，而不是一张大杂烩。",
			Body: skillMD("拼贴叙事板",
				"用户丢来很多风格参考时使用。",
				"1. 每张参考只学一件事。\n2. 图层职责。\n3. 统一纸色或胶片底。",
				"拼贴规范。",
				"不要平均融合所有参考。")},
		{ID: "creative-head-turns", Name: "转头与视线", Tag: "creative", Cover: cover(2), Likes: 280, Added: 520,
			Desc: "规定视线方向和转头幅度，避免面瘫或乱瞟。",
			Body: skillMD("转头与视线",
				"角色发呆、对不上戏时使用。",
				"1. 看向谁。\n2. 转头速度。\n3. 眨眼。",
				"表演提示。",
				"不要无动机扫视镜头。")},
		{ID: "creative-scale-cue", Name: "尺度提示", Tag: "creative", Cover: cover(3), Likes: 230, Added: 430,
			Desc: "用一只手、一扇门、一把椅告诉模型物体有多大。",
			Body: skillMD("尺度提示",
				"商品巨大或角色比例漂时使用。",
				"1. 放一个已知尺度的参照。\n2. 镜头不要太广导致畸变骗尺度。",
				"带尺度的提示词。",
				"不要只写巨大或微小。")},
		{ID: "social-yt-coldopen", Name: "长视频冷开场", Tag: "social", Cover: cover(4), Likes: 410, Added: 760,
			Desc: "YouTube 式前八秒：承诺、证据、为何是现在。",
			Body: skillMD("长视频冷开场",
				"超过一分钟的口播或教程时使用。",
				"1. 一句承诺。\n2. 一个可见证据。\n3. 目录只提即将发生的。",
				"开场 8 秒脚本。",
				"不要先自我介绍三十秒。")},
		{ID: "social-loop", Name: "循环短视频", Tag: "social", Cover: cover(5), Likes: 360, Added: 670,
			Desc: "让结尾接回开头，形成可循环观看。",
			Body: skillMD("循环短视频",
				"需要刷完还想再看一遍时使用。",
				"1. 首尾同一动作或构图。\n2. 中段只推进一件事。",
				"循环结构。",
				"不要结尾淡出黑场。")},
		{ID: "social-podcast-clip", Name: "播客切片", Tag: "social", Cover: cover(6), Likes: 250, Added: 470,
			Desc: "从长对谈抽出 30–45 秒可独立成立的冲突。",
			Body: skillMD("播客切片",
				"有访谈或口播长稿时使用。",
				"1. 选一个观点冲突。\n2. 给反应镜头。\n3. 切在句子气口。",
				"切片脚本。",
				"不要从中间半句话开始。")},
		{ID: "social-thumbnail", Name: "封面构图（无字）", Tag: "social", Cover: cover(7), Likes: 330, Added: 610,
			Desc: "为封面留表情和色块，文字交给后期。",
			Body: skillMD("封面构图（无字）",
				"需要封面或缩略图时使用。",
				"1. 一张脸或一只手。\n2. 强色块。\n3. 明确无文字。",
				"封面提示词。",
				"不要让模型写标题。")},
		{ID: "social-series-recap", Name: "系列回顾卡", Tag: "social", Cover: cover(8), Likes: 210, Added: 390,
			Desc: "把往期钩子压成五秒，服务新观众。",
			Body: skillMD("系列回顾卡",
				"栏目化账号的新一期开头使用。",
				"1. 人设一句。\n2. 上期物件。\n3. 本期问题。",
				"五秒回顾。",
				"不要每期重做片头动画。")},
		{ID: "social-duet-structure", Name: "对拍/接龙结构", Tag: "social", Cover: cover(9), Likes: 190, Added: 360,
			Desc: "给对拍留下半屏或反应位，不抢对方的信息。",
			Body: skillMD("对拍/接龙结构",
				"需要反应、补充或演示对照时使用。",
				"1. 原视频信息在哪一侧。\n2. 反应只做一个点。\n3. 结尾提出下一步。",
				"对拍分镜。",
				"不要同时讲两个新观点。")},
		{ID: "social-community", Name: "社区征集脚本", Tag: "social", Cover: cover(10), Likes: 180, Added: 340,
			Desc: "征集一个具体物件或动作，而不是空泛互动。",
			Body: skillMD("社区征集脚本",
				"要评论、投稿或 UGC 时使用。",
				"1. 示范一次。\n2. 规则一句话。\n3. 画面停在空白处。",
				"征集 15 秒。",
				"不要说请一键三连。")},
		{ID: "social-endcard", Name: "片尾信息架构", Tag: "social", Cover: cover(11), Likes: 200, Added: 380,
			Desc: "片尾只留一个下一步：下集、评论或系列。",
			Body: skillMD("片尾信息架构",
				"完播后不知去哪时使用。",
				"1. 一个行动。\n2. 画面静止。\n3. 不堆三个按钮文案给模型写。",
				"片尾 3 秒。",
				"不要同时求关注、求评论、求分享。")},
		{ID: "social-text-safe-hook", Name: "花字安全钩子", Tag: "social", Cover: cover(12), Likes: 270, Added: 500,
			Desc: "钩子画面为花字留位置，生成时仍禁止出字。",
			Body: skillMD("花字安全钩子",
				"短视频需要大花字时使用。",
				"1. 人物偏下。\n2. 上三分之一干净。\n3. 无文字。",
				"钩子构图。",
				"不要生成乱码字幕。")},
		{ID: "others-qc-slate", Name: "成片质检清单", Tag: "others", Cover: cover(13), Likes: 260, Added: 490,
			Desc: "检查换脸、跳轴、乱码字、水印和声画错位。",
			Body: skillMD("成片质检清单",
				"导出前或用户觉得哪里不对时使用。",
				"1. 角色是否同一人。\n2. 有无乱码文字。\n3. 轴线。\n4. 声画是否同场景。",
				"质检表。",
				"没有成片时不要假装看过。")},
		{ID: "others-naming", Name: "镜头命名规范", Tag: "others", Cover: cover(14), Likes: 180, Added: 340,
			Desc: "统一文件和节点名：集-场-镜-版本。",
			Body: skillMD("镜头命名规范",
				"画布节点或导出文件开始混乱时使用。",
				"1. EP01-S03-SH12-v3。\n2. 角色名用资产 id。\n3. 不要用最终、最新。",
				"命名表。",
				"不要用表情符号当文件名。")},
		{ID: "others-export-spec", Name: "导出规格卡", Tag: "others", Cover: cover(15), Likes: 170, Added: 320,
			Desc: "按平台写画幅、时长、字幕安全和音量。",
			Body: skillMD("导出规格卡",
				"同一条片子要发多平台时使用。",
				"1. 画幅。\n2. 时长上限。\n3. 字幕安全区。\n4. 不让模型烧录文字。",
				"规格卡。",
				"不要假设未配置的平台接口。")},
		{ID: "others-privacy-faces", Name: "可识别真人规避", Tag: "others", Cover: cover(16), Likes: 210, Added: 400,
			Desc: "避免在世明星脸和可识别路人，改写成类型化外形。",
			Body: skillMD("可识别真人规避",
				"提示词疑似点名明星或街拍路人时使用。",
				"1. 改成类型化骨相。\n2. 去掉姓名。\n3. 路人背面或虚化。",
				"改写提示词。",
				"不要提供模仿在世明星的方法。")},
		{ID: "others-access-captions", Name: "无障碍字幕", Tag: "others", Cover: cover(17), Likes: 160, Added: 300,
			Desc: "给听障观众准备对白、声源和关键音效标注。",
			Body: skillMD("无障碍字幕",
				"成片要烧录或导出字幕时使用。",
				"1. 对白。\n2. 说话人。\n3. 关键音效。\n4. 行长限制。",
				"字幕轴。",
				"不要用表情包代替声源说明。")},
		{ID: "others-prompt-version", Name: "提示词版本记录", Tag: "others", Cover: cover(18), Likes: 190, Added: 360,
			Desc: "每次改提示词只改一个变量，并记下结果。",
			Body: skillMD("提示词版本记录",
				"反复生成仍不稳定时使用。",
				"1. 锁主体。\n2. 一次只改光线或景别。\n3. 记录保留项。",
				"版本笔记。",
				"不要一次改十个形容词。")},
		{ID: "others-budget-gen", Name: "生成预算分配", Tag: "others", Cover: cover(0), Likes: 150, Added: 280,
			Desc: "先定妆和主场景，再覆盖镜头，避免把次数花在废镜。",
			Body: skillMD("生成预算分配",
				"次数有限或结果很散时使用。",
				"1. 角色定妆。\n2. 主场景。\n3. 关键动作。\n4. 最后才做空镜。",
				"生成顺序。",
				"不要先批量出五十张风格测试。")},
		{ID: "others-archive", Name: "素材归档规则", Tag: "others", Cover: cover(1), Likes: 140, Added: 260,
			Desc: "把可用、候选、淘汰分开，归档进本地素材库。",
			Body: skillMD("素材归档规则",
				"画布和素材库开始重复时使用。",
				"1. 可用：确认状态。\n2. 候选：草案。\n3. 淘汰：归档。\n4. 标题写清职责。",
				"归档清单。",
				"不要把淘汰和定妆放同一文件夹。")},
		{ID: "others-legal-mark", Name: "商标与标识检查", Tag: "others", Cover: cover(2), Likes: 170, Added: 320,
			Desc: "提示词和画面避免真实商标、车牌和可识别店招。",
			Body: skillMD("商标与标识检查",
				"街景、包装、服装有品牌嫌疑时使用。",
				"1. 改成虚构标识。\n2. 车牌不可读。\n3. 包装用几何色块。",
				"规避改写。",
				"不要教人假冒真实商标。")},
		{ID: "others-sound-beds", Name: "环境声床", Tag: "others", Cover: cover(3), Likes: 160, Added: 300,
			Desc: "给场景指定一层稳定环境声，避免只有音乐。",
			Body: skillMD("环境声床",
				"画面有空间但声音发空时使用。",
				"1. 空间声（雨、空调、街）。\n2. 偶发声。\n3. 音乐后入。",
				"声床说明。",
				"不要用音乐代替空间。")},
		{ID: "others-ref-weights", Name: "参考图权重", Tag: "others", Cover: cover(4), Likes: 220, Added: 410,
			Desc: "多张参考时规定构图、光线、表演各学哪张。",
			Body: skillMD("参考图权重",
				"参考图互相打架时使用。",
				"1. 构图一张。\n2. 光线一张。\n3. 表演一张。\n4. 写不学什么。",
				"权重说明。",
				"不要平均融合。")},
	}
}
