package video

func skillCategories() []map[string]any {
	return []map[string]any{
		{"value": "drama", "label": "短剧影视"},
		{"value": "ecommerce", "label": "电商营销"},
		{"value": "creative", "label": "创意设计"},
		{"value": "social", "label": "社媒内容"},
		{"value": "others", "label": "其他"},
	}
}

type canvasSkillDef struct {
	ID, Name, Tag, Desc, Cover, Body string
	Likes, Added                     int
}

func skillMD(title, when, steps, output, forbid string) string {
	return "# " + title + "\n\n## 何时使用\n" + when + "\n\n## 步骤\n" + steps + "\n\n## 输出\n" + output + "\n\n## 禁止\n" + forbid + "\n"
}

func builtinCanvasSkills() []canvasSkillDef {
	covers := []string{
		"/short-drama-styles/cyberpunk-neon.jpg",
		"/short-drama-styles/retro-hong-kong.jpg",
		"/short-drama-styles/suspense-noir.jpg",
		"/short-drama-styles/fantasy-3d.jpg",
		"/short-drama-styles/storybook-fantasy.jpg",
		"/short-drama-styles/urban-live-action.jpg",
		"/short-drama-styles/future-tech.jpg",
		"/short-drama-styles/nature-healing.jpg",
		"/short-drama-styles/real-life.jpg",
		"/short-drama-styles/black-white-noir.jpg",
		"/short-drama-styles/period-live-action.jpg",
		"/short-drama-styles/space-opera.jpg",
		"/short-drama-styles/clay-stop-motion.jpg",
		"/short-drama-styles/ink-narrative.jpg",
		"/short-drama-styles/chinese-2d.jpg",
		"/short-drama-styles/surreal-dream.jpg",
		"/short-drama-styles/comic-pop.jpg",
		"/short-drama-styles/three-d-cartoon.jpg",
		"/short-drama-styles/warm-interior.jpg",
	}
	cover := func(i int) string { return covers[i%len(covers)] }
	core := []canvasSkillDef{
		{ID: "drama-storyboard", Name: "短剧分镜拆镜", Tag: "drama", Cover: cover(0), Likes: 1280, Added: 2460,
			Desc: "把剧本拆成 8–15 秒镜头任务，每镜含 2–4 个分切。",
			Body: skillMD("短剧分镜拆镜",
				"进入分镜阶段、已有剧本或对白时使用。",
				"1. 先读角色、场景、道具清单，锁定身份名称。\n2. 按时长规划：总秒数 ≈ 字数 / 500 × 60，镜数 ≈ 总秒数 / 12。\n3. 每条任务 8–15 秒；过渡 8–10，叙事 10–15，高潮 12–15。\n4. description 内用【镜头1】【镜头2】写画面（人物+动作+身体+脸），对白写成「角色名说：『…』」，旁白写成「旁白：…」。\n5. 绑定 scene_id 与 character_ids / prop_ids。",
				"分镜表：镜号、时长、景别、运镜、对白、绑定资产。",
				"不要旁白式讲解过程；不要把整集写成一个镜头。")},
		{ID: "drama-extractor", Name: "剧本资产抽取", Tag: "drama", Cover: cover(1), Likes: 980, Added: 1880,
			Desc: "从正文抽出角色、场景、道具，并给出可复用设定卡。",
			Body: skillMD("剧本资产抽取",
				"拿到小说、剧本或大纲，需要建立短剧资产库时使用。",
				"1. 列出所有有名字或反复出现的人物，写年龄、关系、外形、标志服饰。\n2. 列出地点：室内外、时间、光线、可拍摄证据。\n3. 列出关键道具及其叙事职责。\n4. 标注主角/配角、主场景/过场。",
				"三张表：角色、场景、道具，每条含 id 建议名、描述、出现集数。",
				"不要发明原文没有的人物；不要用网红脸模板替代外形。")},
		{ID: "drama-script-rewriter", Name: "对白可拍改写", Tag: "drama", Cover: cover(2), Likes: 860, Added: 1640,
			Desc: "把小说叙述改成可实拍对白与动作，藏住真正目的。",
			Body: skillMD("对白可拍改写",
				"小说腔太重、对白在解释情节、或一场戏缺少可见动作时使用。",
				"1. 先写这场戏的人物目的、隐瞒信息和场景限制。\n2. 把心理活动改成动作、停顿、视线和道具。\n3. 对白只说人物此刻会说的话，不总结主题。\n4. 用一个可见行动完成转折。",
				"一场戏：场景头、动作、对白、潜台词注释（给导演看，不进字幕）。",
				"不要让角色互相告知观众已知信息；不要写成旁白小说。")},
		{ID: "drama-prompt-character", Name: "角色一致性提示", Tag: "drama", Cover: cover(3), Likes: 740, Added: 1520,
			Desc: "把角色卡写成可跨镜复用的外形与衣橱提示词。",
			Body: skillMD("角色一致性提示",
				"生成角色定妆、转面或跨集换装前使用。",
				"1. 固定骨相、年龄、发型、体型、标志配饰。\n2. 按季节/职业写衣橱编号，而不是每次随机服装。\n3. 写清正侧背必须一致的结构。\n4. 列出禁用：网红脸、年龄漂移、乱换发型。",
				"一段可直接粘贴的角色提示词 + 衣橱版本表。",
				"不要模仿现有明星或版权角色。")},
		{ID: "drama-prompt-scene", Name: "场景置景提示", Tag: "drama", Cover: cover(4), Likes: 690, Added: 1410,
			Desc: "把地点写成可拍的空间、材质、光线与生活痕迹。",
			Body: skillMD("场景置景提示",
				"需要建立主场景、过场或空镜库时使用。",
				"1. 写清地域、年代、室内外、时间、天气。\n2. 材质板：墙、地面、家具、标识。\n3. 光源必须有出处。\n4. 用道具留下人物痕迹，而不是空洞样板间。",
				"场景提示词 + 平面关系一句话 + 禁用清单。",
				"不要把中国城市写成欧美街道；不要无来源霓虹。")},
		{ID: "drama-prompt-prop", Name: "关键道具提示", Tag: "drama", Cover: cover(5), Likes: 420, Added: 880,
			Desc: "给线索道具唯一外观、磨损和跨集状态。",
			Body: skillMD("关键道具提示",
				"案件、信物、信、手机、武器等需要跨集可识别时使用。",
				"1. 外观只保留 2–3 个可记忆特征。\n2. 写使用痕迹与版本（完好/破损/染血）。\n3. 说明它在叙事中的职责。",
				"道具卡：外形、材质、状态版本、出现规则。",
				"不要让每个镜头道具都焕然一新。")},
		{ID: "drama-prompt-video", Name: "镜头提示词导演", Tag: "drama", Cover: cover(6), Likes: 1560, Added: 3120,
			Desc: "把分镜写成模型能执行的画面、运镜、光线提示词。",
			Body: skillMD("镜头提示词导演",
				"分镜已拆好、准备生成视频或图生视频时使用。",
				"1. 先写主体、动作、景别、机位。\n2. 再写运镜（推/拉/摇/跟）和节奏。\n3. 写光线来源与色彩气质，不写滤镜名。\n4. 标明无字幕、无标识、无水印。",
				"一条可生成的中文镜头提示词，可附英文对照。",
				"不要堆砌风格形容词；不要指定版权影片名。")},
		{ID: "drama-coverage", Name: "覆盖镜头方案", Tag: "drama", Cover: cover(7), Likes: 510, Added: 920,
			Desc: "给一场对话戏设计主镜头、反打、插入和过肩。",
			Body: skillMD("覆盖镜头方案",
				"对手戏、审讯、饭桌戏需要可剪辑覆盖时使用。",
				"1. 主镜头交代空间关系。\n2. 正反打保持视线方向。\n3. 插入手、道具、反应。\n4. 标注轴线，避免跳轴。",
				"覆盖表：镜号、机位、轴线、剪辑用途。",
				"不要所有镜头都是特写；不要无动机环绕。")},
		{ID: "drama-color-script", Name: "色彩脚本", Tag: "drama", Cover: cover(8), Likes: 390, Added: 760,
			Desc: "按场次规定主色、强调色和禁用色，服务情绪弧。",
			Body: skillMD("色彩脚本",
				"项目启动或需要统一全片气质时使用。",
				"1. 给全片定 60/30/10 色板。\n2. 按场次写情绪对应的色温。\n3. 强调色只给危险、权力或信物。",
				"色彩脚本表：场次、主色、辅色、强调色、禁用。",
				"不要一场一个滤镜；不要青橙默认。")},
		{ID: "drama-continuity", Name: "连贯性检查", Tag: "drama", Cover: cover(9), Likes: 470, Added: 830,
			Desc: "检查服饰、道具、伤痕、时间线和空间方向是否打架。",
			Body: skillMD("连贯性检查",
				"多集生成后、成片前或用户感到角色换脸时使用。",
				"1. 对照角色衣橱和道具版本。\n2. 检查左右手、门的朝向、天气。\n3. 列出冲突并给出应保留的版本。",
				"问题清单：位置、冲突描述、建议修正。",
				"不要在没有材料时假装看过画面。")},
		{ID: "drama-trailer-cut", Name: "预告片剪辑大纲", Tag: "drama", Cover: cover(10), Likes: 610, Added: 1100,
			Desc: "从成片或分镜抽出 15–45 秒预告结构。",
			Body: skillMD("预告片剪辑大纲",
				"需要预告、片花或投放素材时使用。",
				"1. 钩子 3 秒。\n2. 人物关系 8 秒。\n3. 升级冲突 10 秒。\n4. 悬念定格，不泄结局。",
				"时间轴：秒数、画面、对白/音效、字幕。",
				"不要剧透结局；不要纯空镜堆砌。")},
		{ID: "drama-voice-direction", Name: "配音导演卡", Tag: "drama", Cover: cover(11), Likes: 330, Added: 640,
			Desc: "给角色规定声线、气口、情绪幅度和禁区。",
			Body: skillMD("配音导演卡",
				"准备 TTS 或真人配音前使用。",
				"1. 声线：年龄、气息、语速。\n2. 每场情绪幅度 1–5。\n3. 气口标在长句里。\n4. 禁止播音腔和解释性重音。",
				"角色声线卡 + 本场标注稿。",
				"不要给所有角色同一音色。")},
		{ID: "drama-episode-outline", Name: "单集大纲建筑师", Tag: "drama", Cover: cover(12), Likes: 720, Added: 1340,
			Desc: "把长故事压成可拍的一集：目标、阻碍、反转、钩子。",
			Body: skillMD("单集大纲建筑师",
				"还没有分集、或一集太散时使用。",
				"1. 本集人物目标。\n2. 外部阻碍与内部缺陷。\n3. 中点反转。\n4. 集末钩子必须是可见事件。",
				"一页大纲：A/B 线、场次、钩子。",
				"不要写成全集剧情说明书。")},
		{ID: "drama-180-axis", Name: "轴线与机位图", Tag: "drama", Cover: cover(13), Likes: 280, Added: 510,
			Desc: "用文字机位图保住 180 度轴线和视线。",
			Body: skillMD("轴线与机位图",
				"对手戏、三人戏、车戏容易跳轴时使用。",
				"1. 画（用文字）人物 A/B 与摄影机 1/2/3。\n2. 标明视线。\n3. 越轴必须给中性镜头过渡。",
				"机位图 + 越轴规则。",
				"不要用炫技环绕掩盖跳轴。")},
		{ID: "ecom-15s-ad", Name: "十五秒卖点广告", Tag: "ecommerce", Cover: cover(14), Likes: 1180, Added: 2210,
			Desc: "人群、主张、三镜头结构的短视频广告脚本。",
			Body: skillMD("十五秒卖点广告",
				"需要商品短视频、信息流广告或货架主图视频时使用。",
				"1. 定义人群与使用场景。\n2. 一句主张，不虚构功效。\n3. 三镜头：问题/产品/结果。\n4. 字幕不超过 8 字/行。",
				"15 秒分镜：画面、时长、口播、字幕、音效。",
				"不要编造认证数据；不要堆满花字。")},
		{ID: "ecom-pdp-story", Name: "详情页视觉叙事", Tag: "ecommerce", Cover: cover(15), Likes: 540, Added: 970,
			Desc: "把详情页改成可拍的模块顺序与主视觉。",
			Body: skillMD("详情页视觉叙事",
				"电商详情页、主图或品牌页需要统一视觉时使用。",
				"1. 首屏承诺。\n2. 痛点实证。\n3. 材质/工艺。\n4. 使用场景。\n5. 信任与规格。",
				"模块表：顺序、视觉、文案职责。",
				"不要把详情页做成杂志拼贴。")},
		{ID: "ecom-live-script", Name: "直播切片脚本", Tag: "ecommerce", Cover: cover(16), Likes: 470, Added: 860,
			Desc: "把直播口播切成可投放的 30–60 秒片段。",
			Body: skillMD("直播切片脚本",
				"有口播或需要模拟直播切片时使用。",
				"1. 钩子提问。\n2. 一个卖点实证。\n3. 价格或赠品信息。\n4. 行动号召。",
				"切片脚本：时间、画面、口播、字幕。",
				"不要连续喊麦；不要同时塞三个卖点。")},
		{ID: "ecom-ugc-brief", Name: "UGC 口播简报", Tag: "ecommerce", Cover: cover(17), Likes: 630, Added: 1190,
			Desc: "给达人/口播规定场景、禁忌和必须出镜的信息。",
			Body: skillMD("UGC 口播简报",
				"找达人、拍口播或生成真人风格种草时使用。",
				"1. 真实使用场景，不要影棚。\n2. 必须说出的 3 个信息。\n3. 禁忌：竞品、医疗、绝对化。\n4. 结尾自然展示产品。",
				"一页 brief：场景、台词要点、禁忌、交付规格。",
				"不要写成电视广告腔。")},
		{ID: "ecom-comparison", Name: "对比测评分镜", Tag: "ecommerce", Cover: cover(18), Likes: 360, Added: 640,
			Desc: "公平对比结构，避免变成攻击竞品。",
			Body: skillMD("对比测评分镜",
				"需要测评、前后对比或规格对比时使用。",
				"1. 同一测试条件。\n2. 可见差异只展示可验证项。\n3. 结论落到使用场景，不贬低。",
				"对比表 + 分镜。",
				"不要捏造测试；不要出现真实竞品商标。")},
		{ID: "ecom-sku-hero", Name: "主图英雄镜头", Tag: "ecommerce", Cover: cover(0), Likes: 410, Added: 780,
			Desc: "单品英雄镜头：材质特写、手部交互、环境反光。",
			Body: skillMD("主图英雄镜头",
				"生成商品主图、旋转展示或材质特写时使用。",
				"1. 主体清晰，背景克制。\n2. 手或使用痕迹证明尺度。\n3. 光线服务材质，不整容产品。",
				"3–5 条镜头提示词。",
				"不要过度磨皮和塑料高光。")},
		{ID: "creative-style-bible", Name: "项目美术圣经", Tag: "creative", Cover: cover(1), Likes: 890, Added: 1670,
			Desc: "锁定媒介、色板、角色造型和禁用项，作为全项目基线。",
			Body: skillMD("项目美术圣经",
				"新项目选画风、或生成结果风格漂移时使用。",
				"1. 媒介（实拍/2D/3D/水墨）。\n2. 色板权重。\n3. 角色头身与脸型规则。\n4. 材质与建筑世界观。\n5. 全局禁用。",
				"一页风格规范，可粘贴进画风设置。",
				"不要把单镜头提示词当成项目规范。")},
		{ID: "creative-turnaround", Name: "角色三视图", Tag: "creative", Cover: cover(2), Likes: 760, Added: 1490,
			Desc: "正侧背一致的角色设定，服务后续镜头。",
			Body: skillMD("角色三视图",
				"需要角色设定图、转面或绑定参考时使用。",
				"1. 同一服装、同一比例。\n2. 正面、侧面、背面。\n3. 标注身高关系。\n4. 背景干净，无文字。",
				"三视图提示词。",
				"不要三面三种发型；不要抄已有 IP。")},
		{ID: "creative-lighting", Name: "布光预设导演", Tag: "creative", Cover: cover(3), Likes: 520, Added: 930,
			Desc: "把情绪翻译成主光方向、色温和轮廓光。",
			Body: skillMD("布光预设导演",
				"画面平、或需要统一打光时使用。",
				"1. 主光方位与高度。\n2. 色温。\n3. 是否轮廓光。\n4. 选择一种气质：伦勃朗/逆光/低照度/黄金时刻/冷灰。",
				"打光提示词，可对应画布打光面板。",
				"不要同时堆所有灯光风格。")},
		{ID: "creative-animatic", Name: "动态分镜节奏", Tag: "creative", Cover: cover(4), Likes: 340, Added: 610,
			Desc: "给静帧序列规定时长、切点和音效，形成 animatic。",
			Body: skillMD("动态分镜节奏",
				"已有分镜图、要预览节奏时使用。",
				"1. 每镜秒数。\n2. 切点落在动作或台词气口。\n3. 标注环境声与音乐起伏。",
				"animatic 时间轴。",
				"不要平均分配时长。")},
		{ID: "creative-title-design", Name: "片头标题系统", Tag: "creative", Cover: cover(5), Likes: 290, Added: 540,
			Desc: "标题、字幕、角标的层级，但不让模型直接写死文字。",
			Body: skillMD("片头标题系统",
				"需要片头、字幕安全区或标题动画时使用。",
				"1. 标题层级。\n2. 安全区。\n3. 出现/消失节奏。\n4. 提示词里要求为文字留白，不生成乱码文字。",
				"标题系统说明 + 生成提示。",
				"不要要求模型渲染可读书名。")},
		{ID: "creative-world-bible", Name: "世界观规则卡", Tag: "creative", Cover: cover(6), Likes: 450, Added: 820,
			Desc: "三条世界规则、代价和视觉证据，避免设定漂移。",
			Body: skillMD("世界观规则卡",
				"仙侠、科幻、悬疑需要稳定规则时使用。",
				"1. 最多三条硬规则。\n2. 每条规则的视觉证据。\n3. 违反规则的代价。",
				"规则卡。",
				"不要一次发明二十种体系。")},
		{ID: "creative-shot-grammar", Name: "景别词典", Tag: "creative", Cover: cover(7), Likes: 380, Added: 700,
			Desc: "把情绪需求翻译成远景/全景/中景/近景/特写。",
			Body: skillMD("景别词典",
				"提示词只有形容词、没有景别时使用。",
				"1. 问这一镜要交代空间、关系还是情绪。\n2. 选景别。\n3. 配运镜。",
				"景别建议 + 改写后的提示词。",
				"不要全片特写。")},
		{ID: "social-douyin-hook", Name: "短视频三秒钩子", Tag: "social", Cover: cover(8), Likes: 1340, Added: 2580,
			Desc: "前三秒用提问、反差或动作抓住停留。",
			Body: skillMD("短视频三秒钩子",
				"做抖音/短视频开头、完播差时使用。",
				"1. 第一帧必须有人的动作或问题。\n2. 三秒内给出为什么继续看。\n3. 不要先片头 logo。",
				"3 个可选钩子 + 对应后续 12 秒。",
				"不要制造虚假焦虑或医疗承诺。")},
		{ID: "social-xhs-carousel", Name: "图文轮播脚本", Tag: "social", Cover: cover(9), Likes: 670, Added: 1210,
			Desc: "小红书式封面主张 + 内页步骤。",
			Body: skillMD("图文轮播脚本",
				"需要图文笔记或轮播封面时使用。",
				"1. 封面一句主张。\n2. 内页每页一个步骤。\n3. 末页总结可执行动作。",
				"封面文案（给设计，不让模型写字）+ 内页提纲。",
				"不要封面堆满字。")},
		{ID: "social-caption-pack", Name: "字幕与标题变体", Tag: "social", Cover: cover(10), Likes: 490, Added: 880,
			Desc: "同一支片子产出多条标题、字幕和话题。",
			Body: skillMD("字幕与标题变体",
				"要发布多平台或 A/B 标题时使用。",
				"1. 5 条标题，长度分区。\n2. 口播字幕断句。\n3. 话题 8 个以内。",
				"标题/字幕/话题清单。",
				"不要刷屏重复 emoji。")},
		{ID: "social-broll", Name: "B-roll 空镜清单", Tag: "social", Cover: cover(11), Likes: 310, Added: 560,
			Desc: "为口播准备可剪的空镜、手部和环境。",
			Body: skillMD("B-roll 空镜清单",
				"口播太满、需要画面换气时使用。",
				"1. 手部操作。\n2. 环境建立。\n3. 情绪空镜。\n4. 每条注明时长和声音。",
				"B-roll 列表。",
				"不要只拍漂亮但无关的风景。")},
		{ID: "social-series-bible", Name: "账号系列设定", Tag: "social", Cover: cover(12), Likes: 400, Added: 730,
			Desc: "固定人设、片头结构、更新节奏，做成系列而不是单条。",
			Body: skillMD("账号系列设定",
				"要做栏目化短视频时使用。",
				"1. 人设一句话。\n2. 每期结构。\n3. 视觉识别（服装/角落/音乐）。\n4. 更新节奏。",
				"系列圣经一页。",
				"不要每期换人设。")},
		{ID: "social-comment-hook", Name: "评论区互动钩", Tag: "social", Cover: cover(13), Likes: 270, Added: 490,
			Desc: "片尾提问设计，服务评论而不是结束。",
			Body: skillMD("评论区互动钩",
				"需要互动、投票或征集素材时使用。",
				"1. 二选一问题。\n2. 或征集一个具体物件。\n3. 画面停在提问。",
				"片尾 5 秒脚本。",
				"不要空泛的「你们觉得呢」。")},
		{ID: "others-prompt-critic", Name: "提示词外科手术", Tag: "others", Cover: cover(14), Likes: 820, Added: 1540,
			Desc: "诊断失败提示词：冲突指令、缺主体、缺镜头。",
			Body: skillMD("提示词外科手术",
				"生成结果跑偏、糊、换脸或风格乱时使用。",
				"1. 圈出互相打架的词。\n2. 补主体、动作、景别、光线。\n3. 删掉无效风格堆砌。\n4. 给出改写版。",
				"诊断 + 改写后的提示词。",
				"不要在没看到原提示词时假装诊断。")},
		{ID: "others-film-critic", Name: "镜头诊断评论", Tag: "others", Cover: cover(15), Likes: 560, Added: 1010,
			Desc: "从叙事、人物、构图、运镜、声音给可拍摄的修改。",
			Body: skillMD("镜头诊断评论",
				"审剧本、分镜或成片时使用。",
				"1. 先索取材料。\n2. 五维各给一条引用。\n3. 每条给可执行改法。",
				"带引用的修改意见。",
				"没有材料时不要假装看过。")},
		{ID: "others-sfx-cue", Name: "声音设计清单", Tag: "others", Cover: cover(16), Likes: 250, Added: 470,
			Desc: "对白、环境、拟音、音乐分层，避免全靠 BGM。",
			Body: skillMD("声音设计清单",
				"成片干、或只有音乐没有空间时使用。",
				"1. 对白干声。\n2. 环境层。\n3. 动作拟音。\n4. 音乐只在情绪需要时进入。",
				"声音轴。",
				"不要全程垫同一首情绪音乐。")},
		{ID: "others-subtitle-timing", Name: "字幕时码", Tag: "others", Cover: cover(17), Likes: 230, Added: 430,
			Desc: "按气口断句、控制行长，给烧录或后期。",
			Body: skillMD("字幕时码",
				"有口播、需要字幕轴时使用。",
				"1. 按呼吸断句。\n2. 每行不超过 14 个汉字。\n3. 对白与旁白分开样式说明。",
				"粗时码表。",
				"不要把整段独白塞进一条字幕。")},
		{ID: "others-safety-brief", Name: "生成安全简报", Tag: "others", Cover: cover(18), Likes: 190, Added: 360,
			Desc: "列出未成年人、暴力、商标、可识别真人等禁区。",
			Body: skillMD("生成安全简报",
				"题材敏感或提示词可能越界时使用。",
				"1. 检查年龄。\n2. 检查真实商标与明星。\n3. 检查过度血腥。\n4. 给出可拍的替代写法。",
				"风险清单 + 替代提示。",
				"不要提供违法内容的实现方法。")},
		{ID: "others-reference-board", Name: "参考板策展", Tag: "others", Cover: cover(0), Likes: 440, Added: 790,
			Desc: "把参考图分成构图、光线、色彩、表演四栏，避免混用。",
			Body: skillMD("参考板策展",
				"用户丢来一堆参考图时使用。",
				"1. 分类：构图/光线/色彩/表演。\n2. 每类只留 2 张。\n3. 写清学什么、不学什么。",
				"参考板说明。",
				"不要把所有参考平均融进一个提示词。")},
		{ID: "others-shot-list-export", Name: "拍摄清单导出", Tag: "others", Cover: cover(1), Likes: 300, Added: 550,
			Desc: "把画布节点整理成可执行的拍摄/生成顺序。",
			Body: skillMD("拍摄清单导出",
				"画布节点很多、需要开工顺序时使用。",
				"1. 按场次编组。\n2. 先定妆与主场景，再覆盖镜头。\n3. 标依赖（角色必须先于该镜头）。",
				"有序 shot list。",
				"不要按节点创建时间当拍摄顺序。")},
		{ID: "others-model-brief", Name: "渠道能力对照", Tag: "others", Cover: cover(2), Likes: 210, Added: 400,
			Desc: "根据镜头需求选择图、视频还是文本，而不是一个模型打天下。",
			Body: skillMD("渠道能力对照",
				"用户问该用图还是视频、或结果类型不对时使用。",
				"1. 要运动用视频。\n2. 要定妆/三视图用图。\n3. 要结构/对白用文本。\n4. 对照当前已配置渠道说话，不假设未接入的第三方服务。",
				"建议媒体类型 + 提示词形态。",
				"不要编造未配置的模型名称。")},
	}
	return append(core, extraCanvasSkills(cover)...)
}
