import { type Copy } from "./copy";

export const zhCN = {
  app: {
    setupBanner: "先设置工作区和 API key，再发第一轮。",
    openControl: "打开设置",
    dismiss: "关闭",
    retry: "重试",
    applied: "已应用所选 hunk",
    undone: "已还原所选 hunk",
    undo: "撤销",
    controlSaved: "设置已保存",
    checkedOut: "已 checkout",
    rolledBack: "已回滚",
    stagedUpdate: "已应用暂存更新",
    setupFirst: "先在设置里配置工作区。",
    queued: "已排入下一轮",
    steered: "已注入转向",
    compacted: "上下文已压缩",
    deleted: "线程已删除",
    archived: "已归档",
    unarchived: "已取消归档",
    pinned: "已置顶",
    unpinned: "已取消置顶",
    forked: "已复制会话",
    exported: "导出已复制",
    about: "关于",
    quit: "退出",
    turnFinished: "轮次结束",
    approval: "审批",
    errorNotice: "错误",
  },
  dialog: {
    cancel: "取消",
    confirm: "确认",
  },
  rail: {
    newChat: "新对话",
    search: "搜索对话",
    noChats: "还没有对话",
    running: "运行中",
    idle: "空闲",
    archived: "已归档",
    pin: "置顶",
    unpin: "取消置顶",
    archive: "归档",
    unarchive: "取消归档",
    rename: "重命名",
    fork: "复制会话",
    delete: "删除",
    showArchived: "显示已归档",
    hideArchived: "隐藏已归档",
    jump: "跳转",
    more: "会话操作",
    untitled: "未命名对话",
    connected: "已连接",
    disconnected: "未连接",
    isolated: "隔离",
    chats: "对话",
    labs: "实验室",
    settings: "设置",
    control: "设置",
    collapse: "收起侧栏",
    expand: "展开侧栏",
    notifications: "通知",
    noNotifications: "还没有通知",
    clearNotifications: "清空",
    harbor: "Harbor",
    harborHint: "晋升前先跑评测",
    evolve: "Evolve",
    evolveHint: "ACE / DGM 循环",
    harness: "Harness",
    harnessHint: "先进化、再评测、再移动指针",
    stagingDirty: "暂存",
    canaryDirty: "金丝雀",
  },
  transcript: {
    ready: "可以发一轮",
    readyBody: "用 @file:path、@folder:dir 或 @harness 钉上下文。Plan 模式只提议、不写入。",
    working: "工作中…",
    needsApproval: "需要审批",
    mention: "提及",
    thinking: "推理",
    plan: "计划",
    toolsUsed: "{n} 个工具",
    checkpoint: "检查点",
    steer: "转向",
    subagent: "子代理",
    patch: "补丁",
    artifact: "产物",
    openFile: "打开",
    copy: "复制",
    copied: "已复制",
    copyFailed: "复制失败",
    once: "一次",
    session: "本对话",
    always: "总是",
    deny: "拒绝",
    allow: "允许一次",
    allowSession: "本对话",
    allowAlways: "总是允许",
    reject: "拒绝",
    jumpLatest: "跳到最新",
    thoughtFor: "思考了 {n}",
    citations: "引用",
    filesCount: "{n} 个文件",
    toolRunning: "进行中",
    toolDone: "完成",
    toolFailed: "失败",
    retry: "继续本轮",
    errorDetails: "供应商详情",
    errorOverflow: "上下文过长",
    errorOverflowHint: "下一轮会自动压缩。如果反复出现，用 /compact 或开一个新对话。",
    errorAuth: "密钥被拒绝",
    errorAuthHint: "到设置里检查 API key 和 Base URL。",
    errorRateLimit: "请求过于频繁",
    errorRateLimitHint: "稍等片刻再重试。",
    errorInvalid: "供应商拒绝了这一轮",
    errorInvalidHint: "多半是工具历史格式不对。先重试，若仍失败就开新对话。",
    errorTimeout: "请求超时",
    errorTimeoutHint: "模型没有及时返回。",
    errorCanceled: "已停止",
    errorCanceledHint: "这一轮被中断了。",
    errorProvider: "模型接口失败",
    errorProviderHint: "供应商返回了错误。稍后再试。",
    errorBudget: "预算已用尽",
    errorBudgetHint: "在设置里提高预算，或开一个新对话。",
    errorUnknown: "出了点问题",
    errorUnknownHint: "继续本轮即可。",
    starters: [
      { label: "总结工作区", text: "Summarize this workspace and list the files that matter." },
      { label: "钉住 harness", text: "@harness\nWhat is the active harness and what can I safely change?" },
      { label: "规划一次改动", text: "Propose a plan to add a README section describing how to run Yoyo desktop." },
    ],
  },
  composer: {
    placeholder: "给 Yoyo 发消息",
    disabled: "在设置里配置工作区后才能发送…",
    enter: "Enter 发送",
    queueHint: "Enter 会排到当前轮之后",
    planHint: "只读并提议。写入需等待。",
    workspaceRequired: "需要工作区",
    agent: "Agent",
    plan: "Plan",
    send: "发送",
    queue: "排队",
    queuedCount: "{n} 条等待中",
    stop: "停止",
    steer: "转向",
    mention: "插入提及",
    attach: "附加文件",
    clipboard: "粘贴剪贴板",
    screenshot: "截屏",
    more: "更多",
    mentions: "提及",
    commands: "命令",
    message: "消息",
    model: "模型",
    context: "上下文",
    ctxSystem: "系统",
    ctxTools: "工具",
    ctxDynamic: "工作记忆",
    ctxChat: "对话",
    ctxFree: "剩余",
    ctxWindow: "窗口",
    ctxElided: "已省略",
    ctxProvider: "供应商",
    mentionFile: "钉一个文件（有界）",
    mentionFolder: "钉目录列表",
    mentionSkill: "注入 skill 正文",
    mentionHarness: "注入当前 harness 摘要",
  },
  slash: {
    new: "新对话",
    rename: "重命名对话",
    fork: "复制对话",
    archive: "归档对话",
    delete: "删除对话",
    plan: "切换 Plan 模式",
    diff: "刷新审阅 diff",
    steer: "给正在跑的一轮转向",
    compact: "压缩上下文",
    model: "设置对话模型",
    export: "导出 Markdown",
    stop: "停止当前轮",
    quit: "退出 Yoyo",
    schedule: "创建心跳或 cron 任务",
    remember: "暂存一条记忆",
    forget: "遗忘一条记忆",
    project: "创建个人 OS 项目",
    artifact: "要一份文档/表格/幻灯产物",
  },
  review: {
    diff: "Diff",
    files: "文件",
    context: "上下文",
    ask: "审批",
    refresh: "刷新",
    apply: "应用所选",
    unified: "统一",
    split: "分栏",
    noHunks: "没有 hunk。先跑一轮，再刷新。",
    noFiles: "当前 diff 没有改动文件。",
    tokens: "Tokens",
    budget: "预算",
    elided: "已省略",
    contextNote: "受信任的钉会跨轮保留。工具记录是不受信任的工作记忆。",
    noAsk: "没有待审批。流内卡片会出现在 transcript。",
    toggle: "切换审查",
    tabs: "审查",
    queue: "队列",
    noQueue: "没有草稿、浏览器动作或收件箱项。",
    diffLayout: "Diff 布局",
    contextMoved: "用量显示在输入框下方。",
    once: "一次",
    session: "本会话",
    always: "总是",
    deny: "拒绝",
    quote: "引用到 composer",
    openReview: "在 Review 打开",
  },
  trace: {
    tab: "轨迹",
    refresh: "刷新",
    empty: "还没有事件。跑一轮就会记下轨迹。",
    noSession: "选一个对话来看它的轨迹。",
    events: "事件",
    tools: "调用",
    errors: "错误",
    tokens: "Tokens",
    duration: "耗时",
    spilled: "Spill",
    artifacts: "产物",
    timeline: "时间线",
    filterAll: "全部",
    filterExec: "调用",
    filterDialog: "对话",
    filterMemory: "记忆",
    filterError: "错误",
    copy: "复制",
    copied: "已复制",
    loadSpill: "完整产物",
    truncated: "已截断",
    bytes: "字节",
    noMatch: "这个筛选下没有事件。",
  },
  control: {
    title: "Control",
    hint: "Vault、策略、更新器。Agent 不能改这些面。",
    appearance: "外观",
    appearanceHint: "主题跟窗口走，不跟 agent。",
    provider: "提供商",
    providerHint: "密钥留在 vault。Agent 读不到。",
    workspace: "工作区",
    workspaceHint: "轮次对着这个目录跑。",
    policy: "策略",
    policyHint: "默认拒绝，除非你打开。预算是硬停。",
    plugins: "插件",
    pluginsHint: "WASM 保持 HighRisk + ForceAsk。没有 WASI 文件系统。",
    colorMode: "颜色模式",
    resolved: "当前",
    captionFollow: "标题按钮和窗口背景跟随此项。",
    model: "模型",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "粘贴后保存 — 写入 vault",
    extraModels: "额外模型 (BoN)",
    path: "路径",
    autoAllow: "自动允许 shell（默认拒绝，除非你打开）",
    maxBudget: "最大预算 USD",
    usdPerMtok: "USD / MTok",
    noFibers: "没有额外 fiber。",
    unload: "卸载",
    save: "保存",
    applyUpdate: "应用已暂存更新",
    checkUpdate: "检查暂存更新",
    unsaved: "有未保存更改",
    system: "系统",
    dark: "深色",
    light: "浅色",
    browse: "浏览",
    mcp: "MCP",
    mcpHint: "Stdio 服务器。工具仍走网络门。",
    mcpName: "名称",
    mcpCommand: "命令",
    mcpArgs: "参数",
    mcpStart: "启动",
    mcpStop: "停止",
    logs: "日志",
    logsHint: "Journal 尾部。Agent 不能改这个文件。",
    doctor: "Doctor",
    closeToTray: "关闭到托盘",
    vaultSource: "Vault",
    noMcp: "没有正在运行的 MCP 服务器。",
    shortcuts: "快捷键",
    shortcutsHint: "可改的键盘路径。Agent 不能改 keymap。",
    language: "语言",
    quitRunning: "有轮次仍在运行。确定退出？",
  },
  labs: {
    harbor: "Harbor",
    harborHint: "Held-in 不能掉、held-out 不能掉，safety fail 永不晋升。",
    evolve: "Evolve",
    evolveHint: "ACE 增量写入 playbook。Harbor 仍拥有 refs/active。",
    harness: "Harness",
    harnessHint: "只移动指针。loop/policy 拓扑需要 L3。",
    k: "K",
    rounds: "轮数",
    sealed: "密封 20/10",
    runCycle: "跑一轮",
    noCycle: "还没有循环。",
    promoted: "金丝雀",
    parent: "父节点",
    trials: "试验",
    merged: "已合并",
    activeMoved: "已动 active",
    proposal: "提案",
    accepted: "接受",
    reason: "原因",
    in: "In",
    out: "Out",
    playbook: "Playbook",
    archive: "Archive",
    helpful: "有帮助",
    harmful: "有害",
    rejected: "拒绝",
    rollback: "回滚",
    notTrusted: "不可信",
    trusted: "可信",
    checkout: "Checkout",
    diffAsB: "作为 B 对比",
    fieldDiff: "字段 diff",
    hashA: "hash A",
    hashB: "hash B",
    compare: "对比",
    field: "字段",
    from: "From",
    to: "To",
    l3: "L3 checkout",
    busyHarbor: "Harbor 运行中…",
    busyEvolve: "Evolve 运行中…",
  },
  settings: {
    back: "返回",
    title: "设置",
    hint: "Vault、策略、更新器。Agent 不能改这些面。",
    tabs: {
      general: "通用",
      appearance: "外观",
      provider: "提供商",
      policy: "策略",
      isolation: "隔离",
      connectors: "连接器",
      memory: "记忆",
      automations: "自动化",
      mcp: "MCP",
      plugins: "插件",
      shortcuts: "快捷键",
      updates: "更新",
      logs: "日志",
      danger: "危险区",
    },
    sections: {
      generalBasics: "基础",
      generalApp: "应用",
      generalDesktop: "桌面",
      appearanceMode: "颜色模式",
      appearanceLanguage: "语言",
      providerAccount: "账户",
      providerModels: "模型",
      policyGate: "门禁",
      policyBudget: "预算",
      isolationStatus: "诚实状态",
      connectorsCatalog: "账户",
      memoryItems: "条目",
      automationsJobs: "任务",
      mcpServers: "服务器",
      mcpJson: "编辑 JSON",
      pluginsFibers: "Fiber",
      shortcutsMap: "键位",
      updatesChannel: "更新",
      logsJournal: "Journal",
      logsDoctor: "Doctor",
      dangerZone: "不可逆操作",
    },
    workspace: "工作区",
    workspaceDesc: "轮次对着这个目录跑。",
    browse: "浏览",
    language: "语言",
    languageDesc: "界面语言。原生菜单和托盘会立刻跟着切换。",
    closeToTray: "关闭到托盘",
    closeToTrayDesc: "隐藏窗口而不是退出。",
    startAtLogin: "登录时启动",
    startAtLoginDesc: "登录这台电脑时打开 Yoyo。",
    alwaysOnTop: "始终置顶",
    alwaysOnTopDesc: "保持窗口在其他应用之上。",
    notifications: "系统通知",
    notificationsDesc: "轮次结束、审批和错误的系统提示。",
    notifyUnfocused: "仅在失焦时",
    notifyUnfocusedDesc: "窗口聚焦时不发系统通知。",
    uiScale: "界面缩放",
    uiScaleDesc: "壳层尺寸。对话密度保持不变。",
    colorMode: "颜色模式",
    colorModeDesc: "标题按钮和窗口背景跟随此项。",
    system: "系统",
    dark: "深色",
    light: "浅色",
    resolved: "当前",
    provider: "提供商",
    providerDesc: "OpenAI 兼容的 chat completions。选预设会填入 Base URL 和默认模型。",
    providerPreset: "预设填入兼容端点。保存后 key 仍只进 vault。",
    ctxWindow: "上下文窗口",
    outputLimit: "最大输出",
    vision: "视觉",
    reasoning: "推理",
    perMillion: "/MTok",
    modelsCount: "个模型",
    catalogHint: "模型列表和上下文窗口来自 models.dev。点选一个模型作为默认。",
    selectedModel: "默认模型",
    presetHintClaude: "需要 OpenAI 兼容网关，或改用 OpenRouter。",
    presetHintAzure: "把 YOUR_RESOURCE 换成 Azure 资源名。",
    presetHintCustom: "任意 OpenAI 兼容的 /v1/chat/completions 端点。",
    yes: "是",
    no: "否",
    oauth: "OAuth",
    model: "模型",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "粘贴后保存 — 写入 vault",
    extraModels: "额外模型 (BoN)",
    vaultSource: "Vault",
    saveProvider: "保存提供商",
    testConnection: "测试连接",
    testOk: "提供商可达",
    testFail: "提供商检查失败",
    autoAllow: "自动允许 shell",
    autoAllowDesc: "默认拒绝，除非你打开。",
    gateMode: "审批模式",
    gateModeDesc: "Manual 每次询问。AutoSafe 先跑注入/外泄启发式，命中则回退询问。Skip 仅操作者可用，身份动作仍 ForceAsk。",
    gateManual: "手动",
    gateAutoSafe: "AutoSafe",
    gateSkip: "跳过",
    crashResume: "崩溃后续跑",
    crashResumeDesc: "非身份任务在 daemon 崩溃后自动续跑。高风险授权永不恢复。",
    searchUrl: "搜索 API",
    searchUrlDesc: "HTTPS 或带 {q} 的模板。DuckDuckGo 刮页只是 fallback。",
    isolationHint: "只有 OS 隔离器真正包住 shell 时才显示沙箱徽章。Job Object 是进程树遏制，不是沙箱。",
    isolationKind: "隔离器",
    isolationSandbox: "沙箱",
    isolationSigned: "签名",
    isolationVault: "Vault",
    isolationBrowser: "浏览器配置",
    isolationSleep: "本机睡眠会跳过定时任务。常开节点上跑 yoyo daemon。",
    connectorsHint: "OAuth token 进系统凭据库。send_as_you 永远 ForceAsk。",
    connect: "连接",
    memoryHint: "写入只进 staging，晋升才可信。遗忘立即生效。",
    promote: "晋升",
    forget: "遗忘",
    automationsHint: "任务在拷贝工作区跑。不会在未再批的情况下 send_as_you。",
    scheduleKind: "类型",
    scheduleSpec: "规格",
    schedulePrompt: "提示",
    addJob: "添加任务",
    mcpHttp: "MCP HTTP",
    mcpEndpoint: "端点",
    mcpHttpHint: "Streamable HTTP MCP。Token 只在 vault。",
    expertDir: "Expert 包目录",
    expertAdmit: "准入已签名 skill",
    expertHint: "未签名包不能成为 refs/active。",
    maxBudget: "最大预算 USD",
    usdPerMtok: "USD / MTok",
    savePolicy: "保存策略",
    mcpHint: "Stdio 服务器。工具仍走网络门。",
    mcpName: "名称",
    mcpCommand: "命令",
    mcpArgs: "参数",
    mcpStart: "启动",
    mcpStop: "停止",
    noMcp: "没有正在运行的 MCP 服务器。",
    mcpJson: "MCP JSON",
    mcpJsonDesc: "{name, command, args} 数组。会替换当前运行集。",
    applyJson: "应用 JSON",
    noFibers: "没有额外 fiber。",
    unload: "卸载",
    unloadConfirm: "卸载这个 fiber？WASM 保持 HighRisk + ForceAsk。",
    recordHint: "点击绑定，然后按下新快捷键。",
    recording: "按下按键…",
    currentVersion: "当前版本",
    channel: "通道",
    updateUrl: "更新 URL",
    updateUrlDesc: "签名清单。应用前暂存区不可信。",
    checkUpdate: "检查更新",
    applyUpdate: "应用已暂存更新",
    applyUpdateConfirm: "应用暂存二进制？这会改写正在运行的应用。Agent 不能做这件事。",
    noStaged: "没有暂存更新",
    logsHint: "Journal 尾部。Agent 不能改这个文件。",
    follow: "跟随",
    reveal: "在文件夹中显示",
    emptyLogs: "还没有 journal 记录。",
    doctor: "Doctor",
    checkoutConfirm: "Checkout 会移动 harness 指针。loop/policy 拓扑需要 L3。暂存区不可信。",
    checkout: "请在 Harness 中提供 hash 再 checkout。",
    save: "保存",
    unsaved: "有未保存更改",
    english: "English",
    chinese: "中文",
  },
    rsi: {
    title: "Harness",
    hint: "先进化、再评测、再移动指针。staging 始终不可信。",
    overview: "态势",
    propose: "进化",
    prove: "评测",
    promote: "指针",
    overviewHint: "指针在哪，下一步该做什么",
    proposeHint: "ACE 点赞写 staging；evolve 写 canary",
    proveHint: "Harbor：held-in / held-out 不能掉",
    promoteHint: "Checkout 只移动指针。loop/policy 拓扑需要 L3",
    next: "下一步",
    nextEvolve: "staging / canary 没有候选。先跑一轮进化。",
    nextEval: "staging 与 active 不同。checkout 前先跑套件。",
    nextCanaryEval: "canary 与 active 不同。checkout 前先跑 Harbor。",
    nextCheckout: "Harbor 证据干净。可以把 staging checkout 到 active。",
    nextCanaryCheckout: "Harbor 证据干净。可以把 canary checkout 到 active。",
    nextBlocked: "Safety fail — Harbor 不会晋升。",
    nextIdle: "active 可信。要候选时再进化。",
    moreEvals: "更多评测",
    danger: "危险",
    copyHash: "复制哈希",
    copied: "已复制",
    active: "active",
    staging: "staging",
    canary: "canary",
    canaryDirty: "金丝雀",
    head: "HEAD",
    lastEval: "上次 Harbor",
    noRefs: "还没有 harness refs。先 init，再刷新。",
    go: "前往",
  },
  about: {
    title: "关于 Yoyo",
    body: "一个 Go 循环。Harbor 之后才晋升。Vault 和 updater 不给 agent 写。",
    close: "关闭",
  },
  harbor: {
    empty: "冒烟套件：held-in write-hello，held-out write-answer，safety no-escape。密封 20/10/5 可选。",
    noResults: "跑完没有任务行。",
    retry: "重试",
    heldIn: "Held-in",
    heldOut: "Held-out",
    safety: "Safety fail",
    runSuite: "跑套件",
    runSafety: "套件 + safety",
    runTb: "TB 子集",
    runBon: "Best-of-3",
    runModels: "多模型 BoN",
    runSealed: "密封 20/10",
    runTransfer: "迁移",
    modelsPh: "模型 a,b",
    whySafety: "Safety 套件失败 — Harbor 不会晋升。",
    whyEvidence: "这次只是证据。晋升仍需要候选相对 baseline 的非回归门。",
    task: "任务",
    kind: "种类",
    pass: "通过",
    fail: "失败",
    error: "错误",
    runN: "Run",
  },
  palette: {
    title: "命令面板",
    desc: "跳到线程、实验室、设置或动作",
    placeholder: "跳到线程或动作…",
    empty: "无匹配",
    actions: "动作",
    rsi: "RSI",
    chats: "对话",
    settings: "设置",
    newChat: "新对话",
    agent: "Agent",
    openHarness: "打开 Harness",
    refreshDiff: "刷新 diff",
    about: "关于",
    quit: "退出",
    runSuite: "运行评测套件",
    runCycle: "跑一轮进化",
  },
  titlebar: {
    fork: "Fork",
    diff: "Diff",
    live: "运行中",
    rename: "重命名对话",
    inbox: "收件箱",
  },
  dock: {
    chat: "对话",
    expand: "展开",
    toggle: "切换对话栏",
  },
  window: {
    minimise: "最小化",
    maximise: "最大化",
    close: "关闭",
  },
} as unknown as Copy;
