import { type Copy } from "./copy";

export const zhCN = {
  app: {
    setupBanner: "先设置工作区和 API key，再发第一轮。",
    openControl: "打开 Control",
    dismiss: "关闭",
    applied: "已应用所选 hunk",
    undone: "已还原所选 hunk",
    undo: "撤销",
    controlSaved: "Control 已保存",
    checkedOut: "已 checkout",
    rolledBack: "已回滚",
    stagedUpdate: "已应用暂存更新",
    setupFirst: "先在 Control 设置工作区。",
    queued: "已排入下一轮",
    steered: "已注入转向",
    compacted: "上下文已压缩",
    deleted: "线程已删除",
    archived: "已归档",
    pinned: "已置顶",
    exported: "导出已复制",
    about: "关于",
    quit: "退出",
  },
  dialog: {
    cancel: "取消",
    confirm: "确认",
  },
  rail: {
    newChat: "新对话",
    search: "搜索对话",
    noChats: "还没有对话",
    running: "运行中",
    idle: "空闲",
    archived: "已归档",
    pin: "置顶",
    unpin: "取消置顶",
    archive: "归档",
    unarchive: "取消归档",
    rename: "重命名",
    delete: "删除",
    showArchived: "显示已归档",
    labs: "实验室",
    control: "Control",
    harbor: "Harbor",
    harborHint: "晋升前先跑评测",
    evolve: "Evolve",
    evolveHint: "ACE / DGM 循环",
    harness: "Harness",
    harnessHint: "Refs 与 checkout",
  },
  transcript: {
    ready: "可以发一轮",
    readyBody: "用 @file:path、@folder:dir 或 @harness 钉上下文。Plan 模式只提议、不写入。",
    openControl: "打开 Control 设置工作区",
    working: "工作中…",
    needsApproval: "需要审批",
    mention: "提及",
    thinking: "推理",
    plan: "计划",
    subagent: "子代理",
    patch: "补丁",
    copy: "复制",
    once: "一次",
    session: "本会话",
    always: "总是",
    deny: "拒绝",
    starters: [
      { label: "总结工作区", text: "Summarize this workspace and list the files that matter." },
      { label: "钉住 harness", text: "@harness\nWhat is the active harness and what can I safely change?" },
      { label: "规划一次改动", text: "Propose a plan to add a README section describing how to run Yoyo desktop." },
    ],
  },
  composer: {
    placeholder: "给 Yoyo 发消息。/ 命令，@ 钉上下文。",
    disabled: "在 Control 设置工作区后才能发送…",
    enter: "Enter 发送",
    queueHint: "Enter 会排到当前轮之后",
    planHint: "只读并提议。写入需等待。",
    workspaceRequired: "需要工作区",
    agent: "Agent",
    plan: "Plan",
    send: "发送",
    queue: "排队",
    stop: "停止",
    steer: "转向",
    mention: "插入提及",
    attach: "附加文件",
    mentions: "提及",
    commands: "命令",
    message: "消息",
    model: "模型",
  },
  review: {
    diff: "Diff",
    files: "文件",
    context: "上下文",
    ask: "审批",
    refresh: "刷新",
    apply: "应用所选",
    unified: "统一",
    split: "分栏",
    noHunks: "没有 hunk。先跑一轮，再刷新。",
    noFiles: "当前 diff 没有改动文件。",
    tokens: "Tokens",
    budget: "预算",
    elided: "已省略",
    contextNote: "受信任的钉会跨轮保留。工具记录是不受信任的工作记忆。",
    noAsk: "没有待审批。流内卡片会出现在 transcript。",
    toggle: "切换审查",
    once: "一次",
    session: "本会话",
    always: "总是",
    deny: "拒绝",
    quote: "引用到 composer",
    openReview: "在 Review 打开",
  },
  control: {
    title: "Control",
    hint: "Vault、策略、更新器。Agent 不能改这些面。",
    appearance: "外观",
    appearanceHint: "主题跟窗口走，不跟 agent。",
    provider: "提供商",
    providerHint: "密钥留在 vault。Agent 读不到。",
    workspace: "工作区",
    workspaceHint: "轮次对着这个目录跑。",
    policy: "策略",
    policyHint: "默认拒绝，除非你打开。预算是硬停。",
    plugins: "插件",
    pluginsHint: "WASM 保持 HighRisk + ForceAsk。没有 WASI 文件系统。",
    colorMode: "颜色模式",
    resolved: "当前",
    captionFollow: "标题按钮和窗口背景跟随此项。",
    model: "模型",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "粘贴后保存 — 写入 vault",
    extraModels: "额外模型 (BoN)",
    path: "路径",
    autoAllow: "自动允许 shell（默认拒绝，除非你打开）",
    maxBudget: "最大预算 USD",
    usdPerMtok: "USD / MTok",
    noFibers: "没有额外 fiber。",
    unload: "卸载",
    save: "保存",
    applyUpdate: "应用已暂存更新",
    checkUpdate: "检查暂存更新",
    unsaved: "有未保存更改",
    system: "系统",
    dark: "深色",
    light: "浅色",
    browse: "浏览",
    mcp: "MCP",
    mcpHint: "Stdio 服务器。工具仍走网络门。",
    mcpName: "名称",
    mcpCommand: "命令",
    mcpArgs: "参数",
    mcpStart: "启动",
    mcpStop: "停止",
    logs: "日志",
    logsHint: "Journal 尾部。Agent 不能改这个文件。",
    doctor: "Doctor",
    closeToTray: "关闭到托盘",
    vaultSource: "Vault",
    noMcp: "没有正在运行的 MCP 服务器。",
    shortcuts: "快捷键",
    shortcutsHint: "可改的键盘路径。Agent 不能改 keymap。",
    language: "语言",
    quitRunning: "有轮次仍在运行。确定退出？",
  },
  firstRun: {
    title: "设置这台工作站",
    body: "发第一轮前必须有工作区。密钥和模型可以稍后，但路径保存前发送保持禁用。",
    stepWorkspace: "工作区",
    stepKey: "API key",
    stepModel: "模型",
    workspaceHelp: "harness 将读写的绝对路径。",
    keyHelp: "存在 vault。Agent 读不到。可留空，稍后在 Control 粘贴。",
    modelHelp: "提供商模型 id。BoN 额外模型在 Control。",
    next: "下一步",
    back: "上一步",
    finish: "保存并继续",
    skip: "暂时跳过",
    browse: "浏览",
  },
  about: {
    title: "关于 Yoyo",
    body: "一个 Go 循环。Harbor 之后才晋升。Vault 和 updater 不给 agent 写。",
    close: "关闭",
  },
  harbor: {
    empty: "密封本地套件：held-in write-hello，held-out write-answer。TB 子集可选。",
    noResults: "跑完没有任务行。",
    retry: "重试",
    heldIn: "Held-in",
    heldOut: "Held-out",
    safety: "Safety fail",
  },
  palette: {
    title: "命令面板",
    desc: "跳到线程、实验室或动作",
    placeholder: "跳到线程或动作…",
    empty: "无匹配",
  },
  titlebar: {
    fork: "Fork",
    diff: "Diff",
    live: "运行中",
    rename: "重命名对话",
  },
} as unknown as Copy;
