import { type Copy } from "./copy";

export const zhCN = {
  app: {
    skipToContent: "跳到对话",
    setupBanner: "先设置工作区和 API key，再发第一轮。",
    openControl: "打开设置",
    dismiss: "关闭",
    retry: "重试",
    applied: "已应用所选 hunk",
    undone: "已还原所选 hunk",
    undo: "撤销",
    controlSaved: "设置已保存",
    checkedOut: "已 checkout",
    rolledBack: "已回滚",
    stagedUpdate: "已应用暂存更新",
    setupFirst: "先在设置里配置工作区。",
    queued: "已排入下一轮",
    worktreeApplied: "已把 worktree 合回原工作区",
    steered: "已注入转向",
    compacted: "上下文已压缩",
    deleted: "线程已删除",
    archived: "已归档",
    unarchived: "已取消归档",
    pinned: "已置顶",
    unpinned: "已取消置顶",
    forked: "已复制会话",
    exported: "导出已复制",
    dumped: "Dump 路径已复制",
    about: "关于",
    quit: "退出",
    turnFinished: "轮次结束",
    approval: "审批",
    errorNotice: "错误",
  },
  presence: {
    booting: "正在醒来…",
    listening: "在听",
    speaking: "在说",
    thinking: "在想",
    approval: "等你点头",
    refused: "这件事做不了",
    error: "出了点问题",
    recover: "缓一缓",
    loading: "正在处理…",
    stop: "停下了",
    receive: "收到",
    reply: "在写",
    think: "在想",
    done: "做完了",
    pleased: "不错。",
    wake: "嘿",
    sleep: "Zzz",
    idle: "在呢",
    working: "干活中",
    eval: "在跑评测",
    evolve: "在进化",
    ask: "有个问题",
  },
  dialog: {
    cancel: "取消",
    confirm: "确认",
  },
  rail: {
    newChat: "新对话",
    search: "搜索对话…",
    noChats: "还没有对话",
    running: "运行中",
    continueLast: "继续上次",
    interrupted: "中断",
    queued: "排队",
    idle: "空闲",
    archived: "已归档",
    pin: "置顶",
    unpin: "取消置顶",
    archive: "归档",
    unarchive: "取消归档",
    rename: "重命名",
    fork: "复制会话",
    copyId: "复制会话 ID",
    copied: "已复制",
    copy: "复制",
    meta: "会话",
    sessionId: "会话 ID",
    created: "创建",
    workspace: "工作区",
    model: "模型",
    delete: "删除",
    showArchived: "显示已归档",
    hideArchived: "隐藏已归档",
    jump: "跳转",
    more: "会话操作",
    untitled: "未命名对话",
    connected: "已连接",
    disconnected: "未连接",
    isolated: "隔离",
    chats: "对话",
    sessions: "会话",
    sessionsHint: "这个工作区里的对话",
    spaces: "空间",
    newInSpace: "在这里开对话",
    labs: "实验室",
    settings: "设置",
    control: "设置",
    collapse: "收起侧栏",
    expand: "展开侧栏",
    notifications: "通知",
    noNotifications: "还没有通知",
    clearNotifications: "清空",
    harbor: "Harbor",
    harborHint: "晋升前先跑评测",
    evolve: "Evolve",
    evolveHint: "ACE / DGM 循环",
    harness: "Harness",
    harnessHint: "先进化、再评测、再移动指针",
    stagingDirty: "暂存",
    canaryDirty: "金丝雀",
    pinned: "置顶",
    today: "今天",
    yesterday: "昨天",
    earlier: "更早",
    project: "项目",
    skills: "技能",
    skillsHint: "已安装包与 Work Buddy 目录",
    video: "视频",
    videoHint: "对话页。模式在输入框左下角。",
    popOut: "弹出窗口",
    openEditor: "在编辑器打开",
    openTerminal: "在终端打开",
    openFolder: "在文件夹中显示",
    isolator: "隔离器",
  },
  transcript: {
    ready: "今天想先做什么？",
    helloMorning: "早上好。",
    helloAfternoon: "下午好。",
    helloEvening: "晚上好。",
    workingIn: "工作区",
    hintSend: "发送",
    hintMention: "钉上下文",
    hintPlan: "切换 Plan",
    hintVideoMode: "左下角切换模式和剧集",
    videoReady: "先贴一章原文。",
    canvasReady: "描述一个空间镜头。",
    creativeReady: "描述一段短片。",
    working: "工作中…",
    needsApproval: "需要审批",
    mention: "提及",
    thinking: "推理",
    plan: "计划",
    toolsUsed: "{n} 个工具",
    checkpoint: "检查点",
    steer: "转向",
    subagent: "子代理",
    openChild: "打开子抄本",
    patch: "补丁",
    artifact: "产物",
    openFile: "打开",
    copy: "复制",
    copied: "已复制",
    copyFailed: "复制失败",
    copyCode: "复制代码",
    copyTable: "复制表格",
    once: "一次",
    session: "本对话",
    always: "总是",
    deny: "拒绝",
    allow: "允许一次",
    allowSession: "本对话",
    allowAlways: "总是允许",
    reject: "拒绝",
    jumpLatest: "跳到最新",
    thoughtFor: "思考了 {n}",
    citations: "引用",
    filesCount: "{n} 个文件",
    preview: "预览",
    hidePreview: "收起",
    mcpApp: "MCP 视图",
    openPdf: "打开 PDF",
    source: "源码",
    binaryFile: "二进制文件",
    playbookDelta: "Playbook 已更新",
    toolRunning: "进行中",
    toolDone: "完成",
    toolFailed: "失败",
    toolInterrupted: "已中断",
    workedFor: "工作了 {n}",
    steps: "{n} 步",
    failedCount: "{n} 个失败",
    showSteps: "展开步骤",
    hideSteps: "收起步骤",
    live: {
      read: "正在读取",
      edit: "正在编辑",
      search: "正在搜索",
      run: "正在运行",
      web: "正在联网",
      list: "正在浏览目录",
      plan: "正在规划",
      skill: "正在加载技能",
      think: "正在思考",
      other: "正在调用 {name}",
    },
    tally: {
      read: ["读取 1 个文件", "读取 {n} 个文件"],
      edit: ["编辑 1 个文件", "编辑 {n} 个文件"],
      search: ["搜索 1 次", "搜索 {n} 次"],
      run: ["运行 1 条命令", "运行 {n} 条命令"],
      web: ["联网 1 次", "联网 {n} 次"],
      list: ["浏览 1 个目录", "浏览 {n} 个目录"],
      plan: ["更新了计划", "更新计划 {n} 次"],
      skill: ["加载 1 个技能", "加载 {n} 个技能"],
      think: ["进行了推理", "推理 {n} 次"],
      other: ["1 次工具调用", "{n} 次工具调用"],
    },
    retry: "继续本轮",
    details: "详情",
    errorDetails: "供应商详情",
    errorOverflow: "上下文过长",
    errorOverflowHint: "下一轮会自动压缩。如果反复出现，用 /compact 或开一个新对话。",
    errorAuth: "密钥被拒绝",
    errorAuthHint: "到设置里检查 API key 和 Base URL。",
    errorRateLimit: "请求过于频繁",
    errorRateLimitHint: "稍等片刻再重试。",
    errorInvalid: "供应商拒绝了这一轮",
    errorInvalidHint: "多半是工具历史格式不对。先重试，若仍失败就开新对话。",
    errorTimeout: "请求超时",
    errorTimeoutHint: "模型没有及时返回。",
    errorCanceled: "已停止",
    errorCanceledHint: "这一轮被中断了。",
    errorProvider: "模型接口失败",
    errorProviderHint: "供应商返回了错误。稍后再试。",
    errorBudget: "预算已用尽",
    errorBudgetHint: "在设置里提高预算，或开一个新对话。",
    errorMaxTurns: "达到轮次上限",
    errorMaxTurnsHint: "循环在模型完成前停下了。点“继续本轮”接着跑。",
    errorUnknown: "出了点问题",
    errorUnknownHint: "继续本轮即可。",
    starters: [
      { label: "先看看这是什么", hint: "摸清仓库结构", text: "Summarize this workspace and list the files that matter." },
      { label: "给我讲讲", hint: "当前 harness 能做什么", text: "@harness\nWhat is the active harness and what can I safely change?" },
      { label: "先起一份计划", hint: "只读，动手前先商量", text: "Propose a plan to add a README section describing how to run Yoyo desktop." },
    ],
    videoStarters: [
      { label: "改写这一集", hint: "原文改成短剧剧本", text: "把当前集的原文改写成短剧剧本。" },
      { label: "提取资产", hint: "角色、场景、道具", text: "从剧本提取角色、场景和道具。" },
      { label: "拆这一章", hint: "每镜 8 到 15 秒", text: "把剧本拆成分镜，每镜 8 到 15 秒。" },
    ],
    canvasStarters: [
      { label: "远景建立镜头", hint: "黄昏时的安静街道", text: "黄昏时一条安静街道的远景建立镜头。" },
      { label: "环绕静帧", hint: "门口角色的慢绕", text: "缓慢环绕站在门口的角色。" },
    ],
    creativeStarters: [
      { label: "五秒短片", hint: "雨水打在玻璃上", text: "雨水打在玻璃上，浅景深，五秒。" },
      { label: "产品转台", hint: "柔和棚灯，四秒", text: "柔和棚灯下的产品转台，四秒。" },
    ],
  },
  composer: {
    placeholder: "想做什么就说。输入 @ 可以提及文件。",
    placeholderDrama: "贴一章原文，或问这一集…",
    placeholderCanvas: "描述一个空间镜头…",
    placeholderCreative: "描述一段短片…",
    disabled: "在设置里配置工作区后才能发送…",
    enter: "Enter 发送",
    queueHint: "Enter 会排到当前轮之后",
    planHint: "只读并提议。写入需等待。",
    taskPlanProgress: "{done}/{total}",
    showPlan: "展开计划",
    hidePlan: "收起计划",
    planPending: "待办",
    planActive: "进行中",
    planDone: "已完成",
    workspaceRequired: "需要工作区",
    agent: "Agent",
    plan: "Plan",
    mode: "模式",
    agentHint: "跑工具并写入。",
    send: "发送",
    queue: "排队",
    queuedCount: "{n} 条等待中",
    stop: "停止",
    steer: "转向",
    mention: "插入提及",
    attach: "附加文件",
    clipboard: "粘贴剪贴板",
    screenshot: "截屏",
    add: "添加",
    more: "更多",
    mentions: "提及",
    commands: "命令",
    message: "消息",
    model: "模型",
    context: "上下文",
    ctxSystem: "系统",
    ctxTools: "工具",
    ctxDynamic: "工作记忆",
    ctxChat: "对话",
    ctxFree: "剩余",
    ctxWindow: "窗口",
    ctxElided: "已省略",
    ctxProvider: "供应商",
    ctxCache: "缓存",
    ctxCacheUnknown: "供应商未报告",
    mentionFile: "钉一个文件（有界）",
    mentionFolder: "钉目录列表",
    mentionSkill: "注入 skill 正文",
    mentionHarness: "注入当前 harness 摘要",
    mentionKindFile: "文件",
    mentionKindFolder: "文件夹",
    mentionKindSkill: "Skill",
    mentionKindHarness: "Harness",
    mentionEmpty: "没有匹配",
    mentionType: "输入以搜索文件",
    authMode: "授权模式",
    authDefault: "默认",
    authAutoEdit: "自动编辑",
    authFull: "完全访问",
    authAsk: "每次询问",
    workspace: "工作空间",
    workspaceHint: "这个对话的工具、文件和补丁在这里跑。",
    browseWorkspace: "选择文件夹…",
    isolate: "Worktree",
    isolateOn: "隔离检出",
    isolateOff: "写回原工作区",
    isolateHint: "工具在 git worktree 里跑。合回会把隔离检出拷回原工作区。",
    applyWorktree: "把 worktree 合回原工作区",
    queueCancel: "从队列移除",
    queueUp: "提前",
    queueDown: "延后",
  },
  slash: {
    new: "新对话",
    rename: "重命名对话",
    fork: "复制对话",
    archive: "归档对话",
    delete: "删除对话",
    plan: "切换 Plan 模式",
    diff: "刷新审阅 diff",
    steer: "给正在跑的一轮转向",
    compact: "压缩上下文",
    rewind: "回退文件、对话，或两者",
    context: "查看窗口构成和 token",
    model: "设置对话模型",
    export: "导出 Markdown 和 dump 路径",
    stop: "停止当前轮",
    quit: "退出 Yoyo",
    schedule: "创建心跳或 cron 任务",
    remember: "写入记忆（profile … 立即钉住）",
    forget: "遗忘一条记忆",
    project: "创建个人 OS 项目",
    artifact: "要一份文档/表格/幻灯产物",
  },
  review: {
    diff: "Diff",
    files: "文件",
    file: "文件",
    changesTab: "变更",
    context: "上下文",
    ask: "审批",
    refresh: "刷新",
    apply: "应用所选",
    unified: "统一",
    split: "分栏",
    noHunks: "工作区还没有改动。",
    noHunksHint: "树上的标记是本地改动。点文件看全文，或切到 Diff。",
    noFiles: "还没有改动的文件。",
    noTree: "这个工作区还没有文件。",
    noTreeHint: "给对话指定一个文件夹后，就可以像编辑器一样浏览。",
    changes: "{files} 个文件 · {hunks} 个 hunk",
    hunksCount: "{n} 个 hunk",
    hunkOne: "1 个 hunk",
    applyN: "应用 {n} 项",
    clear: "清除",
    selectFile: "选中此文件的全部 hunk",
    approvals: "审批",
    inbox: "收件箱",
    drafts: "草稿",
    browserActions: "浏览器",
    nothingWaiting: "没有需要你处理的事项。",
    open: "打开",
    tokens: "Tokens",
    budget: "预算",
    elided: "已省略",
    contextNote: "受信任的钉会跨轮保留。工具记录是不受信任的工作记忆。",
    noAsk: "没有待审批。流内卡片会出现在 transcript。",
    toggle: "切换审查",
    tabs: "审查",
    queue: "队列",
    noQueue: "审批、收件箱和草稿会汇集到这里。",
    diffLayout: "Diff 布局",
    contextMoved: "用量显示在输入框下方。",
    once: "一次",
    session: "本会话",
    always: "总是",
    deny: "拒绝",
    quote: "引用到 composer",
    openReview: "在 Review 打开",
    browser: "浏览器",
    browserIdle: "隔离浏览器空闲。",
    browserIdleHint: "Agent 打开的页面和写出的 HTML 会出现在这里。登录或验证码时点接管。",
    takeOver: "接管",
    takingOver: "正在打开可见窗口…",
    liveLane: "实况",
    isolatedLane: "隔离档",
    attachedLane: "已登录档",
    headedLane: "可见窗口",
    snapshot: "快照",
    page: "页面",
    waitingFrame: "正在等待隔离页…",
    skills: "技能",
    memory: "记忆",
    pin: "钉选",
    unpin: "取消钉选",
    loaded: "本轮已加载",
    pinned: "已钉选",
    inspect: "查看",
    noSkills: "这个工作区磁盘上没有 skill。",
    noMemory: "还没有记忆。",
    noMemoryHint: "Agent 学到的东西先进入暂存区，值得保留的再晋升。",
    staging: "暂存",
    trusted: "可信",
    promote: "晋升",
    forget: "遗忘",
    dismiss: "忽略",
    openThread: "打开对话",
  },
  trace: {
    tab: "轨迹",
    refresh: "刷新",
    empty: "还没有事件。跑一轮就会记下轨迹。",
    noSession: "选一个对话来看它的轨迹。",
    events: "事件",
    tools: "调用",
    errors: "错误",
    tokens: "Tokens",
    duration: "耗时",
    spilled: "Spill",
    artifacts: "产物",
    timeline: "时间线",
    filterAll: "全部",
    filterExec: "调用",
    filterDialog: "对话",
    filterMemory: "记忆",
    filterError: "错误",
    copy: "复制",
    copied: "已复制",
    sessionId: "会话 ID",
    copyId: "复制会话 ID",
    loadSpill: "完整产物",
    truncated: "已截断",
    bytes: "字节",
    noMatch: "这个筛选下没有事件。",
  },
  control: {
    title: "Control",
    hint: "Vault、策略、更新器。Agent 不能改这些面。",
    appearance: "外观",
    appearanceHint: "主题跟窗口走，不跟 agent。",
    provider: "提供商",
    providerHint: "密钥留在 vault。Agent 读不到。",
    workspace: "工作区",
    workspaceHint: "默认对着这个目录跑。每个对话可以覆盖。",
    policy: "策略",
    policyHint: "默认拒绝，除非你打开。预算是硬停。",
    plugins: "插件",
    pluginsHint: "WASM 保持 HighRisk + ForceAsk。没有 WASI 文件系统。",
    colorMode: "颜色模式",
    resolved: "当前",
    captionFollow: "标题按钮和窗口背景跟随此项。",
    model: "模型",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "粘贴后保存 — 写入 vault",
    extraModels: "额外模型 (BoN)",
    path: "路径",
    autoAllow: "自动允许 shell（默认拒绝，除非你打开）",
    maxBudget: "最大预算 USD",
    usdPerMtok: "USD / MTok",
    noFibers: "没有额外 fiber。",
    unload: "卸载",
    save: "保存",
    applyUpdate: "应用已暂存更新",
    checkUpdate: "检查暂存更新",
    unsaved: "有未保存更改",
    system: "系统",
    dark: "深色",
    light: "浅色",
    browse: "浏览",
    mcp: "MCP",
    mcpHint: "Stdio 服务器。工具仍走网络门。",
    mcpName: "名称",
    mcpCommand: "命令",
    mcpArgs: "参数",
    mcpStart: "启动",
    mcpStop: "停止",
    logs: "日志",
    logsHint: "进程诊断。密钥和对话正文已脱敏。",
    doctor: "Doctor",
    closeToTray: "关闭到托盘",
    vaultSource: "Vault",
    noMcp: "没有正在运行的 MCP 服务器。",
    shortcuts: "快捷键",
    shortcutsHint: "可改的键盘路径。Agent 不能改 keymap。",
    language: "语言",
    quitRunning: "有轮次仍在运行。确定退出？",
  },
  labs: {
    harbor: "Harbor",
    harborHint: "Held-in 不能掉、held-out 不能掉，safety fail 永不晋升。",
    evolve: "Evolve",
    evolveHint: "ACE 增量写入 playbook。Harbor 仍拥有 refs/active。",
    harness: "Harness",
    harnessHint: "只移动指针。loop/policy 拓扑需要 L3。",
    k: "K",
    rounds: "轮数",
    sealed: "密封 12/8/10",
    runCycle: "跑一轮",
    noCycle: "还没有循环。",
    promoted: "金丝雀",
    parent: "父节点",
    trials: "试验",
    merged: "已合并",
    activeMoved: "已动 active",
    proposal: "提案",
    accepted: "接受",
    reason: "原因",
    in: "In",
    out: "Out",
    hit: "命中",
    miss: "未中",
    spend: "花费",
    usd: "美元",
    tokens: "Tokens",
    wall: "墙钟",
    behavior: "行为探针",
    index: "Index 迁移",
    baselines: "BoN / IID / SCS",
    maxUsd: "美元上限",
    goNoGo: "只有 evolve 的 held-out 增益稳定压过 BoN 与 IID，才继续搜。否则冻结搜索结构。",
    labCompare: "同预算对照",
    bon: "Best-of-N",
    iid: "IID",
    scs: "SCS",
    playbook: "Playbook",
    archive: "Archive",
    helpful: "有帮助",
    harmful: "有害",
    rejected: "拒绝",
    rollback: "回滚",
    notTrusted: "不可信",
    trusted: "可信",
    checkout: "Checkout",
    diffAsB: "作为 B 对比",
    fieldDiff: "字段 diff",
    hashFields: "哈希字段",
    hashA: "hash A",
    hashB: "hash B",
    compare: "对比",
    field: "字段",
    from: "从",
    to: "到",
    l3: "L3 checkout",
    busyHarbor: "Harbor 运行中…",
    busyEvolve: "Evolve 运行中…",
    timeline: "版本时间线",
    thisCycle: "本轮",
    playbookDelta: "Playbook 增量",
    noDelta: "本轮没有合并 bullet。",
    moveActive: "把 active 移到这里",
    compareStaging: "对比 staging 与 active",
    ceremony: "Checkout 是人闸。Staging 不可信。",
    advancedHashes: "对比任意两个 hash",
  },
  settings: {
    back: "返回",
    title: "设置",
    hint: "Vault、策略、更新器。Agent 不能改这些面。",
    groups: {
      app: "应用",
      agent: "智能体",
      system: "系统",
    },
    tabs: {
      general: "通用",
      appearance: "外观",
      shortcuts: "快捷键",
      provider: "模型",
      generation: "生成",
      policy: "安全",
      extensions: "扩展",
      personal: "个人",
      advanced: "高级",
    },
    tabHints: {
      general: "任务在哪里跑，以及桌面应用的行为。",
      appearance: "模式、色板、语言和界面尺寸。Agent 不会改这些。",
      shortcuts: "可重映射的键盘路径。Agent 不能改键位。",
      provider: "Key 只留在 vault 里，Agent 读不到。",
      generation: "短剧工坊的图片、语音与视频适配器，以及无限画布协议渠道。密钥只进 vault。",
      policy: "默认拒绝，除非你打开。预算是硬上限。",
      extensions: "额外的工具和账户，都仍然走网络门。",
      personal: "Yoyo 记住什么，以及按计划跑什么。",
      advanced: "更新器、诊断和不可逆操作。",
    },
    sections: {
      generalWorkspace: "工作区",
      generalNotifications: "通知",
      generalDesktop: "桌面",
      appearanceTheme: "颜色模式",
      appearancePalette: "色板",
      appearanceDisplay: "显示",
      shortcutsMap: "键位",
      providerAccount: "接入",
      providerModels: "模型目录",
      providerVideo: "图片、语音与视频",
      generationStudio: "工坊",
      generationCanvas: "画布额外通道",
      generationImage: "图片",
      generationVideo: "视频",
      generationSpeech: "语音",
      generationStyles: "风格",
      policyGate: "审批",
      policyBudget: "预算",
      policyIsolation: "运行环境",
      extensionsMcp: "MCP 服务器",
      extensionsFibers: "插件",
      extensionsConnectors: "已连接账户",
      personalMemory: "记忆",
      personalJobs: "定时任务",
      advancedUpdates: "更新",
      advancedLogs: "诊断",
      advancedJournal: "Journal",
      advancedDoctor: "Doctor",
      advancedDanger: "不可逆操作",
    },
    keys: {
      palette: "命令面板",
      newChat: "新建对话",
      control: "打开设置",
      toggleReview: "切换审阅面板",
      once: "允许一次",
      session: "本会话允许",
      always: "始终允许",
      deny: "拒绝",
    },
    search: "搜索设置…",
    searchEmpty: "没有匹配的设置项。",
    discard: "放弃更改",
    saveChanges: "保存更改",
    editJson: "用 JSON 编辑",
    addServer: "添加服务器",
    noConnectors: "还没有连接任何账户。",
    noMemory: "还没有记住任何东西。",
    noJobs: "没有定时任务。",
    fibersHint: "WASM 保持 HighRisk + ForceAsk，没有 WASI 文件系统。",
    memoryPlaceholder: "希望 Yoyo 记住的事…",
    workspace: "工作区",
    workspaceDesc: "Agent 新对话的默认目录。每个 Agent 对话可以选自己的工作空间。",
    videoWorkspace: "视频工作区",
    videoWorkspaceDesc: "视频模块自己的默认目录，不和 Agent 工作区混用。",
    browse: "浏览",
    language: "语言",
    languageDesc: "界面语言。原生菜单和托盘会立刻跟着切换。",
    closeToTray: "关闭到托盘",
    closeToTrayDesc: "隐藏窗口而不是退出。",
    companion: "桌面伴侣",
    companionDesc: "和主窗口一起待在桌面上。托盘菜单一个开关即可显示或隐藏。不占任务栏，通知会打到宠物身上。",
    startAtLogin: "登录时启动",
    startAtLoginDesc: "登录这台电脑时打开 Yoyo。",
    alwaysOnTop: "始终置顶",
    alwaysOnTopDesc: "保持窗口在其他应用之上。",
    notifications: "系统通知",
    notificationsDesc: "轮次结束、审批和错误的系统提示。",
    notifyUnfocused: "仅在失焦时",
    notifyUnfocusedDesc: "窗口聚焦时不发系统通知。",
    uiScale: "界面缩放",
    uiScaleDesc: "壳层尺寸。档位对齐系统缩放，避免半像素发糊。",
    showThinking: "显示思考",
    showThinkingDesc: "把模型的私有推理流进过程轨。默认关闭——不少接口会拒绝 thinking 字段。",
    colorMode: "颜色模式",
    colorModeDesc: "标题按钮和窗口底色跟随此项。",
    system: "系统",
    dark: "深色",
    light: "浅色",
    resolved: "当前",
    palettesDesc: "深浅色板分开保存。壳层用墨，蓝标出进行中和选中。",
    paletteGroupDark: "深色",
    paletteGroupLight: "浅色",
    palettes: {
      ink: "墨黑",
      inkHint: "安静的石头色。暖炭黑。",
      dim: "暗灰",
      dimHint: "略抬高，仍是石头色。",
      slate: "岩板",
      slateHint: "更冷的炭黑。同一支墨。",
      neutral: "中性",
      neutralHint: "画廊灰泥，安静的石头色。",
      paper: "纸色",
      paperHint: "暖笔记本。奶油色，不是黄。",
      mist: "雾白",
      mistHint: "珍珠雾面，接近宣纸。",
    },
    provider: "提供商",
    providerDesc: "OpenAI 兼容的 chat completions。选预设会填入 Base URL 和默认模型。",
    providerPreset: "预设填入兼容端点。保存后 key 仍只进 vault。",
    ctxWindow: "上下文窗口",
    outputLimit: "最大输出",
    vision: "视觉",
    reasoning: "推理",
    perMillion: "/MTok",
    modelsCount: "个模型",
    catalogHint: "模型列表和上下文窗口来自 models.dev。点选一个模型作为默认。",
    selectedModel: "默认模型",
    presetHintClaude: "需要 OpenAI 兼容网关，或改用 OpenRouter。",
    presetHintAzure: "把 YOUR_RESOURCE 换成 Azure 资源名。",
    presetHintCustom: "任意 OpenAI 兼容的 /v1/chat/completions 端点。",
    yes: "是",
    no: "否",
    oauth: "OAuth",
    model: "模型",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "粘贴后保存 — 写入 vault",
    extraModels: "额外模型 (BoN)",
    vaultSource: "Vault",
    saveProvider: "保存提供商",
    testConnection: "测试连接",
    testOk: "提供商可达",
    testFail: "提供商检查失败",
    autoAllow: "自动允许 shell",
    autoAllowDesc: "默认拒绝，除非你打开。",
    gateMode: "审批模式",
    gateModeDesc: "Manual 每次询问。AutoSafe 先跑注入/外泄启发式，命中则回退询问。Skip 仅操作者可用，身份动作仍 ForceAsk。",
    gateManual: "手动",
    gateAutoSafe: "AutoSafe",
    gateSkip: "跳过",
    crashResume: "崩溃后续跑",
    crashResumeDesc: "非身份任务在 daemon 崩溃后自动续跑。高风险授权永不恢复。",
    searchUrl: "搜索 API",
    searchUrlDesc: "HTTPS 或带 {q} 的模板。DuckDuckGo 刮页只是 fallback。",
    isolationHint: "只有 OS 隔离器真正包住 shell 时才显示沙箱徽章。Job Object 是进程树遏制，不是沙箱。",
    isolationKind: "隔离器",
    isolationSandbox: "沙箱",
    isolationSigned: "签名",
    isolationVault: "Vault",
    isolationBrowser: "浏览器配置",
    isolationSleep: "本机睡眠会跳过定时任务。常开节点上跑 yoyo daemon。",
    connectorsHint: "OAuth token 进系统凭据库。send_as_you 永远 ForceAsk。",
    connect: "连接",
    disconnect: "断开",
    oauthCode: "OAuth 授权码",
    oauthClientId: "Client ID",
    completeOAuth: "完成 OAuth",
    webhookJob: "Webhook",
    triggerWebhook: "触发",
    awakeRequired: "本机必须保持唤醒",
    lidCloseStops: "合盖即停",
    memoryHint: "写入只进 staging，晋升才可信。遗忘立即生效。",
    promote: "晋升",
    forget: "遗忘",
    automationsHint: "任务在拷贝工作区跑。本机必须醒着，合盖即停。不会在未再批的情况下 send_as_you。",
    scheduleKind: "类型",
    scheduleSpec: "规格",
    schedulePrompt: "提示",
    addJob: "添加任务",
    mcpHttp: "MCP HTTP",
    mcpEndpoint: "端点",
    mcpHttpHint: "Streamable HTTP MCP。Token 只在 vault。",
    expertDir: "Expert 包目录",
    expertAdmit: "准入已签名 skill",
    expertHint: "未签名包不能成为 refs/active。",
    maxBudget: "最大预算 USD",
    usdPerMtok: "USD / MTok",
    savePolicy: "保存策略",
    mcpHint: "Stdio 服务器。工具仍走网络门。",
    mcpName: "名称",
    mcpCommand: "命令",
    mcpArgs: "参数",
    mcpStart: "启动",
    mcpStop: "停止",
    noMcp: "没有正在运行的 MCP 服务器。",
    mcpJson: "MCP JSON",
    mcpJsonDesc: "{name, command, args} 数组。会替换当前运行集。",
    applyJson: "应用 JSON",
    noFibers: "没有额外 fiber。",
    unload: "卸载",
    unloadConfirm: "卸载这个 fiber？WASM 保持 HighRisk + ForceAsk。",
    recordHint: "点击绑定，然后按下新快捷键。",
    recording: "按下按键…",
    currentVersion: "当前版本",
    channel: "通道",
    updateUrl: "更新 URL",
    updateUrlDesc: "签名清单。应用前暂存区不可信。",
    checkUpdate: "检查更新",
    applyUpdate: "应用已暂存更新",
    applyUpdateConfirm: "应用暂存二进制？这会改写正在运行的应用。Agent 不能做这件事。",
    noStaged: "没有暂存更新",
    logsHint: "进程诊断尾部。密钥和对话正文不会落盘。",
    journalHint: "哈希链审计。Agent 不能改这个文件。",
    follow: "跟随",
    reveal: "在文件夹中显示",
    copyPath: "复制路径",
    filterLevel: "级别",
    exportBundle: "导出支持包",
    diagnoseTurn: "用日志诊断本轮",
    emptyLogs: "还没有诊断记录。",
    emptyJournal: "还没有 journal 记录。",
    pathCopied: "已复制路径",
    exportedBundle: "支持包已写出",
    crashFile: "崩溃文件",
    doctor: "Doctor",
    checkoutConfirm: "Checkout 会移动 harness 指针。loop/policy 拓扑需要 L3。暂存区不可信。",
    checkout: "请在 Harness 中提供 hash 再 checkout。",
    save: "保存",
    unsaved: "有未保存更改",
    english: "English",
    chinese: "中文",
  },
    rsi: {
    title: "Harness",
    hint: "先进化、再评测、再移动指针。staging 始终不可信。",
    overview: "态势",
    propose: "进化",
    prove: "评测",
    promote: "指针",
    overviewHint: "指针在哪，下一步该做什么",
    proposeHint: "ACE 点赞写 staging；evolve 写 canary",
    proveHint: "Harbor：held-in / held-out 不能掉",
    promoteHint: "Checkout 只移动指针。loop/policy 拓扑需要 L3",
    next: "下一步",
    nextEvolve: "staging / canary 没有候选。先跑一轮进化。",
    nextEval: "staging 与 active 不同。checkout 前先跑套件。",
    nextCanaryEval: "canary 与 active 不同。checkout 前先跑 Harbor。",
    nextCheckout: "Harbor 证据干净。可以把 staging checkout 到 active。",
    nextCanaryCheckout: "Harbor 证据干净。可以把 canary checkout 到 active。",
    nextBlocked: "Safety fail — Harbor 不会晋升。",
    nextIdle: "active 可信。要候选时再进化。",
    moreEvals: "更多评测",
    danger: "危险",
    copyHash: "复制哈希",
    copied: "已复制",
    active: "active",
    staging: "staging",
    canary: "canary",
    canaryDirty: "金丝雀",
    head: "HEAD",
    lastEval: "上次 Harbor",
    noRefs: "还没有 harness refs。先 init，再刷新。",
    go: "前往",
    lineage: "进化路径",
    lineageHint: "每个快照列出相对父节点进化了什么。指针只是同一批对象上的标签。",
    seed: "种子",
    noLineage: "还没有从 refs 可达的快照。先 init，再刷新。",
    openStore: "打开仓库",
    openArtifacts: "打开构件",
    vsParent: "相对父节点",
    noChanges: "相对父节点没有材料变化。",
    added: "新增",
    removed: "删除",
    changed: "变更",
    l3: "L3",
    revealFailed: "无法打开 harness 目录。",
  },
  about: {
    title: "关于 Yoyo",
    body: "一个 Go 循环。Harbor 之后才晋升。Vault 和 updater 不给 agent 写。",
    close: "关闭",
  },
  harbor: {
    empty: "冒烟套件：held-in write-hello，held-out write-answer，safety no-escape。密封 12/8/10 可选。",
    noResults: "跑完没有任务行。",
    retry: "重试",
    heldIn: "Held-in",
    heldOut: "Held-out",
    safety: "Safety fail",
    runSuite: "跑套件",
    runSafety: "套件 + safety",
    runTb: "TB 子集",
    runBon: "Best-of-3",
    runModels: "多模型 BoN",
    runSealed: "密封 12/8/10",
    runTransfer: "迁移",
    runIndex: "Index 迁移",
    runBehavior: "行为探针",
    modelsPh: "模型 a,b",
    whySafety: "Safety 套件失败 — Harbor 不会晋升。",
    whyEvidence: "这次只是证据。晋升仍需要候选相对 baseline 的非回归门。",
    task: "任务",
    kind: "种类",
    pass: "通过",
    fail: "失败",
    error: "错误",
    runN: "Run",
    storyHeldIn: "还能否完成训练过的任务？",
    storyHeldOut: "会不会迁移？",
    storySafety: "Safety 一票否决",
    verdict: "结论",
    verdictPromote: "证据允许进入晋升对话。",
    verdictBlock: "已阻断。不要 checkout。",
    verdictIdle: "先跑套件，再移动指针。",
  },
  skills: {
    title: "技能",
    hint: "已安装的技能可在对话里用 @skill 调用。市场会把完整技能目录（SKILL.md 以及 scripts、references、assets）装进 ~/.yoyo/skills。",
    installed: "已安装",
    market: "市场",
    search: "搜索目录…",
    emptyInstalled: "磁盘上还没有技能包。",
    emptyMarket: "目录不可用。检查网络后刷新。",
    refresh: "刷新目录",
    install: "安装",
    installing: "安装中…",
    installedBadge: "已安装",
    uninstall: "移除",
    pinThread: "钉到对话",
    unpinThread: "取消钉选",
    inspect: "查看",
    bundled: "内置",
    home: "Home",
    workspace: "工作区",
    marketSource: "市场",
    cas: "Harness",
    needsShell: "会请求 shell 工具。仍走能力门。",
    scanOk: "扫描通过",
    attribution: "Work Buddy 公开目录（infometa/workbuddyskills）。只落源文件，安装时不跑 zip 可执行文件。",
    count: "{n}",
    featured: "精选",
    all: "全部",
    close: "回到对话",
    noThread: "先打开一个对话再钉技能。",
    loaded: "本轮已加载",
    none: "无",
    repair: "补全包",
    repairing: "补全中…",
    incomplete: "缺少脚本",
    hasScripts: "含脚本",
    files: "{n} 个文件",
    installPartial: "只装上了 SKILL.md，辅助脚本没拉下来。请补全这个包。",
    repaired: "技能包已补全",
  },
  palette: {
    title: "命令面板",
    desc: "跳到线程、实验室、设置或动作",
    placeholder: "跳到线程或动作…",
    empty: "无匹配",
    actions: "动作",
    rsi: "RSI",
    chats: "对话",
    settings: "设置",
    newChat: "新对话",
    agent: "Agent",
    openHarness: "打开 Harness",
    openSkills: "打开技能",
    openVideo: "打开视频",
    videoGroup: "视频",
    videoCreate: "创作",
    videoDrama: "短剧",
    videoCanvas: "无限画布",
    videoAssets: "资产",
    videoPlugins: "插件",
    videoTasks: "创作历史",
    refreshDiff: "刷新 diff",
    about: "关于",
    quit: "退出",
    runSuite: "运行评测套件",
    runCycle: "跑一轮进化",
  },
  titlebar: {
    fork: "Fork",
    diff: "Diff",
    live: "运行中",
    waiting: "等待审批",
    lastTool: "最近工具",
    rename: "重命名对话",
    inbox: "收件箱",
    copyId: "复制会话 ID",
    copiedId: "已复制会话 ID",
  },
  dock: {
    chat: "对话",
    expand: "展开",
    toggle: "切换对话栏",
  },
  video: {
    title: "视频",
    close: "返回",
    modes: "模式",
    drama: "短剧 Agent",
    dramaHint: "小说到成片：剧本、参考图、分镜、拼接。",
    canvas: "无限画布",
    canvasHint: "空间生成工作台：节点、工具、时间线、导演台。",
    canvasMcp: "在画布线程暴露 MCP",
    canvasMcpHint: "默认关闭。画布会话不挂载全局 MCP，除非你打开这项。",
    creative: "创意模式",
    creativeHint: "单段试玩。同一套适配器，稍后接线。",
    later: "创意模式还没接线。短剧工坊和无限画布共用这条基底。",
    soon: "稍后",
    workshop: "工坊",
    workshopHint: "剧本、静帧和成片。",
    noProject: "未选集",
    noCanvas: "未选画布",
    openBoard: "分镜板",
    openCanvas: "打开画布",
    closeBoard: "回到对话",
    shell: "工作台",
    shellLibrary: "资源",
    shellCreate: "创作",
    shellDrama: "短剧",
    shellCanvas: "画布",
    shellAssets: "资产",
    shellSkills: "技能",
    shellPlugins: "插件",
    shellTasks: "创作历史",
    historyHint: "短剧、画布和生成记录都在这里。",
    historyProjects: "项目",
    historyJobs: "生成记录",
    historyEmptyCanvas: "新建的画布会出现在这里。",
    newCanvas: "新建画布",
    pickSeries: "剧集",
    pickEpisode: "集",
    newDrama: "新剧",
    newEpisode: "新一集",
    untitled: "未命名剧集",
    untitledEp: "未命名集",
    import: "导入火宝项目",
    importHint: "只迁剧集，不迁密钥。",
    empty: "还没有剧",
    emptyHint: "先写标题和一章原文，后面的阶段按条走。",
    script: "剧本",
    cast: "资产",
    board: "分镜",
    cut: "成片",
    novel: "原文",
    screenplay: "剧本",
    rewrite: "改写",
    extract: "提取",
    prompts: "提示词",
    stills: "参考图",
    storyboard: "拆镜",
    vprompts: "镜头提示词",
    clips: "出片",
    stitch: "拼接",
    duration: "时长计划",
    chars: "字",
    seconds: "秒",
    segments: "段",
    generate: "生成",
    generateAll: "补齐缺失",
    retry: "重试",
    cancel: "取消",
    upload: "上传静帧",
    bindChat: "把本集绑到对话",
    language: "内容语言",
    style: "风格",
    ratio: "画幅",
    resolution: "分辨率",
    providers: "厂商",
    imageProvider: "生图",
    videoProvider: "生视频",
    missingKey: "到设置 → 生成里写入 vault 密钥。",
    ffmpegMissing: "拼接需要 ffmpeg，或设置 FFMPEG_BIN。",
    noStills: "还没有静帧",
    noClip: "还没有成片",
    characters: "角色",
    scenes: "场景",
    props: "道具",
    mention: "提起资产",
    jobs: "任务",
    queued: "排队",
    running: "进行中",
    polling: "轮询",
    succeeded: "完成",
    failed: "失败",
    selected: "已选镜头",
    export: "拼接所选",
    play: "播放",
    next: "下一步",
    save: "保存",
    delete: "删除",
    locked: "画幅在建剧时锁定",
    dockHint: "对话只对本集开放短剧工具。",
    stageBusy: "阶段进行中…",
    needSession: "先开一个对话，阶段才能绑定线程。",
    needPrompt: "先写镜头提示词或备好参考图。",
    needClips: "先出片再拼接。",
    ffmpeg: "FFmpeg",
    apiKey: "API 密钥",
    episodes: "集",
    bound: "已绑对话",
    confirmDelete: "确认删除",
    selectAll: "全部有片镜头",
    selectNone: "全不选",
    clipCount: "条镜头",
    skipRewrite: "原文当剧本",
    extractChars: "只提角色",
    extractScenes: "只提场景",
    extractProps: "只提道具",
    addCharacter: "加角色",
    addScene: "加场景",
    addProp: "加道具",
    appearance: "外形",
    styling: "服装",
    lighting: "光线",
    finalPrompt: "静帧提示词",
    bindRefs: "镜头参考",
    history: "历史成片",
    setMain: "用作当前",
    download: "下载",
    narrator: "旁白 — 不出静帧",
    durationLabel: "秒",
    editAsset: "编辑",
    noHistory: "还没有历史成片",
    kindImage: "图片",
    kindVideo: "视频",
    kindSpeech: "语音",
    customProvider: "自定义适配器",
    makeDefault: "默认",
    enabled: "启用",
    missingProviders: "生成前请到设置 → 生成里写入图片和视频密钥。",
    openSettings: "打开设置",
    adapterName: "名称",
    modelsCsv: "模型目录",
    noAdapter: "还没有适配器。选一个厂商模板，再写入 vault 密钥。",
    providerHint: "每一行是一个生成适配器。密钥只进 vault。",
    multiAdapterHint: "可以同时加多个适配器，同一厂商也可以有多行。每一行有自己的密钥和模型目录。短剧、创作和画布共用这份列表。",
    canvasChannelsHint: "上面的图片、视频、语音适配器已经接到创作和画布。这里只加那些列表里没有的影策插件。",
    canvasChannelsEmpty: "没有额外通道。上面的图片、视频、语音适配器已经接到创作和画布。",
    defaultModel: "默认模型",
    styleHint: "风格会前缀到静帧提示词。隐藏后不会出现在剧集选择器。",
    styleName: "风格名",
    addStyle: "添加风格",
    unbind: "无",
    keySaved: "已存密钥",
    noKey: "未写入密钥",
    addAdapter: "添加适配器",
    deleteAdapter: "移除这个适配器及其 vault 密钥？",
    vendor: "厂商",
    ffmpegReady: "可用",
    langZh: "中文",
    langEn: "English",
    langOther: "其他",
    speechHint: "语音适配器留给后续配音。短剧成片走视频模型自带音频。",
    hideStyle: "隐藏",
    restoreStyle: "恢复",
    styleValue: "键名",
    templateHint: "从厂商模板开始，再写入密钥。",
    styleHidden: "已隐藏",
    setDefault: "设为默认",
  },
  window: {
    minimise: "最小化",
    maximise: "最大化",
    close: "关闭",
  },
} as unknown as Copy;
