/** English copy. Keys are stable so zh-CN can land without hunting strings. */
export const en = {
  app: {
    setupBanner: "Set a workspace and API key before the first turn.",
    openControl: "Open Control",
    dismiss: "Dismiss",
    applied: "Applied selected hunks",
    undone: "Reverted selected hunks",
    undo: "Undo",
    controlSaved: "Control saved",
    checkedOut: "Checked out",
    rolledBack: "Rolled back",
    stagedUpdate: "Staged update applied",
    setupFirst: "Set a workspace in Control first.",
    queued: "Queued for the next turn",
    steered: "Steering injected",
    compacted: "Context compacted",
    deleted: "Thread deleted",
    archived: "Archived",
    pinned: "Pinned",
    exported: "Copied export",
    about: "About",
    quit: "Quit",
  },
  dialog: {
    cancel: "Cancel",
    confirm: "Confirm",
  },
  rail: {
    newChat: "New chat",
    search: "Search chats",
    noChats: "No chats yet",
    running: "Running",
    idle: "Idle",
    archived: "Archived",
    pin: "Pin",
    unpin: "Unpin",
    archive: "Archive",
    unarchive: "Unarchive",
    rename: "Rename",
    delete: "Delete",
    showArchived: "Show archived",
    labs: "Labs",
    control: "Control",
    harbor: "Harbor",
    harborHint: "Eval before promote",
    evolve: "Evolve",
    evolveHint: "ACE / DGM cycle",
    harness: "Harness",
    harnessHint: "Refs and checkout",
  },
  transcript: {
    ready: "Ready for a turn",
    readyBody: "Pin extra context with @file:path, @folder:dir, or @harness. Plan mode proposes without writing.",
    openControl: "Open Control to set workspace",
    working: "Working…",
    needsApproval: "Needs approval",
    mention: "Mention",
    thinking: "Reasoning",
    plan: "Plan",
    subagent: "Subagent",
    patch: "Patch",
    copy: "Copy",
    once: "Once",
    session: "Session",
    always: "Always",
    deny: "Deny",
    starters: [
      { label: "Summarize the workspace", text: "Summarize this workspace and list the files that matter." },
      { label: "Pin the harness", text: "@harness\nWhat is the active harness and what can I safely change?" },
      { label: "Plan a change", text: "Propose a plan to add a README section describing how to run Yoyo desktop." },
    ],
  },
  composer: {
    placeholder: "Message Yoyo. / commands, @ pins context.",
    disabled: "Set a workspace in Control to send…",
    enter: "Enter to send",
    queueHint: "Enter queues behind the running turn",
    planHint: "Read and propose. Writes wait.",
    workspaceRequired: "Workspace required",
    agent: "Agent",
    plan: "Plan",
    send: "Send",
    queue: "Queue",
    stop: "Stop",
    steer: "Steer",
    mention: "Insert mention",
    attach: "Attach files",
    mentions: "Mentions",
    commands: "Commands",
    message: "Message",
    model: "Model",
  },
  review: {
    diff: "Diff",
    files: "Files",
    context: "Context",
    ask: "Ask",
    refresh: "Refresh",
    apply: "Apply selected",
    unified: "Unified",
    split: "Split",
    noHunks: "No hunks. Run a turn, then refresh.",
    noFiles: "No changed files in the current diff.",
    tokens: "Tokens",
    budget: "Budget",
    elided: "Elided",
    contextNote: "Trusted pins survive every turn. Tool transcript is untrusted working memory.",
    noAsk: "No pending approvals. In-stream cards appear in the transcript.",
    toggle: "Toggle review",
    once: "Once",
    session: "Session",
    always: "Always",
    deny: "Deny",
    quote: "Quote into composer",
    openReview: "Open in Review",
  },
  control: {
    title: "Control",
    hint: "Vault, policy, and updater. The agent cannot change these surfaces.",
    appearance: "Appearance",
    appearanceHint: "Theme follows the window, not the agent.",
    provider: "Provider",
    providerHint: "Keys stay in the vault. The agent cannot read them.",
    workspace: "Workspace",
    workspaceHint: "Turns run against this directory.",
    policy: "Policy",
    policyHint: "Deny-first unless you opt in. Budget is a hard stop.",
    plugins: "Plugins",
    pluginsHint: "WASM stays HighRisk + ForceAsk. No WASI filesystem.",
    colorMode: "Color mode",
    resolved: "Resolved",
    captionFollow: "Caption buttons and window background follow this.",
    model: "Model",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "paste then Save — stored in vault",
    extraModels: "Extra models (BoN)",
    path: "Path",
    autoAllow: "Auto-allow shell (deny-first stays off unless you opt in)",
    maxBudget: "Max budget USD",
    usdPerMtok: "USD per MTok",
    noFibers: "No extra fibers loaded.",
    unload: "Unload",
    save: "Save",
    applyUpdate: "Apply staged update",
    checkUpdate: "Check staged update",
    unsaved: "Unsaved changes",
    system: "System",
    dark: "Dark",
    light: "Light",
    browse: "Browse",
    mcp: "MCP",
    mcpHint: "Stdio servers. Tools stay behind the network gate.",
    mcpName: "Name",
    mcpCommand: "Command",
    mcpArgs: "Args",
    mcpStart: "Start",
    mcpStop: "Stop",
    logs: "Logs",
    logsHint: "Journal tail. The agent cannot edit this file.",
    doctor: "Doctor",
    closeToTray: "Close to tray",
    vaultSource: "Vault",
    noMcp: "No MCP servers running.",
    shortcuts: "Shortcuts",
    shortcutsHint: "Remappable keyboard paths. The agent cannot edit the keymap.",
    language: "Language",
    quitRunning: "A turn is still running. Quit anyway?",
  },
  firstRun: {
    title: "Set up this workstation",
    body: "A workspace is required before a turn. Key and model can wait, but sending stays disabled until the path is saved.",
    stepWorkspace: "Workspace",
    stepKey: "API key",
    stepModel: "Model",
    workspaceHelp: "Absolute path the harness will read and write.",
    keyHelp: "Stored in the vault. The agent cannot read it. Leave blank to paste later in Control.",
    modelHelp: "Provider model id. Extra BoN models live in Control.",
    next: "Next",
    back: "Back",
    finish: "Save and continue",
    skip: "Skip for now",
    browse: "Browse",
  },
  about: {
    title: "About Yoyo",
    body: "One Go loop. Harbor before promote. Vault and updater stay off-agent.",
    close: "Close",
  },
  harbor: {
    empty: "Sealed local suite: held-in write-hello, held-out write-answer. TB subset is opt-in.",
    noResults: "Run finished with no task rows.",
    retry: "Retry",
    heldIn: "Held-in",
    heldOut: "Held-out",
    safety: "Safety fail",
  },
  palette: {
    title: "Command palette",
    desc: "Jump to a thread, lab, or action",
    placeholder: "Jump to a thread or action…",
    empty: "No matches",
  },
  titlebar: {
    fork: "Fork",
    diff: "Diff",
    live: "live",
    rename: "Rename chat",
  },
} as const;

export type Copy = typeof en;

let active: Copy = en;

export function setCopyCatalog(next: Copy) {
  active = next;
}

export function catalog(): Copy {
  return active;
}

export const copy: Copy = new Proxy({} as Copy, {
  get(_target, prop) {
    return (active as Record<PropertyKey, unknown>)[prop];
  },
});
