/** English copy. Keys are stable so zh-CN can land without hunting strings. */
export const en = {
  app: {
    skipToContent: "Skip to conversation",
    setupBanner: "Set a workspace and API key before the first turn.",
    openControl: "Open Settings",
    dismiss: "Dismiss",
    retry: "Retry",
    applied: "Applied selected hunks",
    undone: "Reverted selected hunks",
    undo: "Undo",
    controlSaved: "Settings saved",
    checkedOut: "Checked out",
    rolledBack: "Rolled back",
    stagedUpdate: "Staged update applied",
    setupFirst: "Set a workspace in Settings first.",
    queued: "Queued for the next turn",
    steered: "Steering injected",
    compacted: "Context compacted",
    deleted: "Thread deleted",
    archived: "Archived",
    unarchived: "Unarchived",
    pinned: "Pinned",
    unpinned: "Unpinned",
    forked: "Forked",
    exported: "Copied export",
    about: "About",
    quit: "Quit",
    turnFinished: "Turn finished",
    approval: "Approval",
    errorNotice: "Error",
  },
  presence: {
    booting: "Waking up…",
    listening: "Listening",
    speaking: "Speaking",
    thinking: "Thinking",
    approval: "Needs your OK",
    refused: "Couldn't do that",
    error: "Something broke",
    recover: "Shaking it off",
    loading: "Opening…",
    stop: "Stopped",
    receive: "Got it",
    reply: "Writing",
    think: "Thinking",
    done: "Done",
    pleased: "Nice.",
    wake: "Hey",
    sleep: "Zzz",
    idle: "Around",
    working: "Working",
    eval: "Running eval",
    evolve: "Evolving",
    ask: "Has a question",
  },
  dialog: {
    cancel: "Cancel",
    confirm: "Confirm",
  },
  rail: {
    newChat: "New chat",
    search: "Search chats…",
    noChats: "No chats yet",
    running: "Running",
    idle: "Idle",
    archived: "Archived",
    pin: "Pin",
    unpin: "Unpin",
    archive: "Archive",
    unarchive: "Unarchive",
    rename: "Rename",
    fork: "Fork",
    copyId: "Copy session ID",
    copied: "Copied",
    copy: "Copy",
    meta: "Session",
    sessionId: "Session ID",
    created: "Created",
    workspace: "Workspace",
    model: "Model",
    delete: "Delete",
    showArchived: "Show archived",
    hideArchived: "Hide archived",
    jump: "Jump",
    more: "Chat actions",
    untitled: "Untitled chat",
    connected: "Connected",
    disconnected: "Disconnected",
    isolated: "isolated",
    chats: "Chats",
    spaces: "Spaces",
    newInSpace: "New chat here",
    labs: "Labs",
    settings: "Settings",
    control: "Settings",
    collapse: "Collapse sidebar",
    expand: "Expand sidebar",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    clearNotifications: "Clear",
    harbor: "Harbor",
    harborHint: "Eval before promote",
    evolve: "Evolve",
    evolveHint: "ACE / DGM cycle",
    harness: "Harness",
    harnessHint: "Propose, prove, then move pointers",
    stagingDirty: "staging",
    canaryDirty: "canary",
    pinned: "Pinned",
    today: "Today",
    yesterday: "Yesterday",
    earlier: "Earlier",
    project: "Project",
    skills: "Skills",
    skillsHint: "Installed packs and Work Buddy catalog",
    video: "Video",
    videoHint: "Conversation. Mode lives on the composer.",
    popOut: "Pop out",
    openEditor: "Open in editor",
    openTerminal: "Open in terminal",
    openFolder: "Show in folder",
    isolator: "isolator",
  },
  transcript: {
    ready: "What are we doing today?",
    helloMorning: "Morning.",
    helloAfternoon: "Good afternoon.",
    helloEvening: "Evening.",
    workingIn: "Working in",
    hintSend: "sends",
    hintMention: "pins context",
    hintPlan: "toggles Plan",
    hintVideoMode: "mode and episode on the composer",
    videoReady: "Paste a chapter.",
    canvasReady: "Describe a spatial shot.",
    creativeReady: "Describe a clip.",
    working: "Working…",
    needsApproval: "Needs approval",
    mention: "Mention",
    thinking: "Reasoning",
    plan: "Plan",
    toolsUsed: "{n} tools",
    checkpoint: "Checkpoint",
    steer: "Steer",
    subagent: "Subagent",
    patch: "Patch",
    artifact: "Artifact",
    openFile: "Open",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Could not copy",
    copyCode: "Copy code",
    copyTable: "Copy table",
    once: "Once",
    session: "This chat",
    always: "Always",
    deny: "Deny",
    allow: "Allow once",
    allowSession: "This chat",
    allowAlways: "Always",
    reject: "Reject",
    jumpLatest: "Jump to latest",
    thoughtFor: "Thought for {n}",
    citations: "Citations",
    filesCount: "{n} files",
    preview: "Preview",
    hidePreview: "Hide",
    mcpApp: "MCP view",
    openPdf: "Open PDF",
    source: "Source",
    binaryFile: "Binary file",
    playbookDelta: "Playbook updated",
    toolRunning: "Running",
    toolDone: "Done",
    toolFailed: "Failed",
    toolInterrupted: "Interrupted",
    workedFor: "Worked for {n}",
    steps: "{n} steps",
    failedCount: "{n} failed",
    showSteps: "Show steps",
    hideSteps: "Hide steps",
    live: {
      read: "Reading",
      edit: "Editing",
      search: "Searching",
      run: "Running",
      web: "Browsing",
      list: "Listing",
      plan: "Planning",
      skill: "Loading skill",
      think: "Thinking",
      other: "Using {name}",
    },
    tally: {
      read: ["Read 1 file", "Read {n} files"],
      edit: ["Edited 1 file", "Edited {n} files"],
      search: ["1 search", "{n} searches"],
      run: ["Ran 1 command", "Ran {n} commands"],
      web: ["1 web lookup", "{n} web lookups"],
      list: ["Listed 1 folder", "Listed {n} folders"],
      plan: ["Updated the plan", "Updated the plan {n} times"],
      skill: ["Loaded 1 skill", "Loaded {n} skills"],
      think: ["Reasoned", "Reasoned {n} times"],
      other: ["1 tool call", "{n} tool calls"],
    },
    retry: "Continue this turn",
    details: "Details",
    errorDetails: "Provider details",
    errorOverflow: "Context too large",
    errorOverflowHint: "Yoyo will compact on the next send. If this persists, run /compact or start a new chat.",
    errorAuth: "Provider rejected the key",
    errorAuthHint: "Check the API key and base URL in Settings.",
    errorRateLimit: "Rate limited",
    errorRateLimitHint: "Wait a moment, then retry.",
    errorInvalid: "The provider rejected this turn",
    errorInvalidHint: "Usually a malformed tool history. Retry; start a new chat if it repeats.",
    errorTimeout: "Request timed out",
    errorTimeoutHint: "The model did not respond in time.",
    errorCanceled: "Stopped",
    errorCanceledHint: "This turn was interrupted.",
    errorProvider: "The model endpoint failed",
    errorProviderHint: "The provider returned an error. Retry in a moment.",
    errorBudget: "Budget reached",
    errorBudgetHint: "Raise the session budget in Settings, or start a new chat.",
    errorMaxTurns: "Reached the turn limit",
    errorMaxTurnsHint: "The loop stopped before the model finished. Continue this turn to keep going.",
    errorUnknown: "Something went wrong",
    errorUnknownHint: "Continue this turn.",
    starters: [
      { label: "What's in here?", hint: "Map the repo in one pass", text: "Summarize this workspace and list the files that matter." },
      { label: "Walk me through it", hint: "The active harness, plainly", text: "@harness\nWhat is the active harness and what can I safely change?" },
      { label: "Sketch a plan first", hint: "Read-only until you say go", text: "Propose a plan to add a README section describing how to run Yoyo desktop." },
    ],
    videoStarters: [
      { label: "Rewrite this episode", hint: "Source into a short-drama beat", text: "Rewrite the current episode's source into a short-drama screenplay." },
      { label: "Extract the cast", hint: "Characters, scenes, props", text: "Extract characters, scenes, and props from the screenplay." },
      { label: "Board this chapter", hint: "Shots of 8 to 15 seconds", text: "Split the screenplay into 8–15 second shots." },
    ],
    canvasStarters: [
      { label: "Wide establishing shot", hint: "Quiet street at dusk", text: "A wide establishing shot of a quiet city street at dusk." },
      { label: "Orbit a still", hint: "Slow circle on a doorway", text: "Orbit slowly around a character standing in a doorway." },
    ],
    creativeStarters: [
      { label: "Five-second clip", hint: "Rain on glass, shallow focus", text: "A 5 second clip of rain on a window, shallow focus." },
      { label: "Product turntable", hint: "Soft studio light, four seconds", text: "A product turntable shot, soft studio light, 4 seconds." },
    ],
  },
  composer: {
    placeholder: "Ask for anything. Type @ to mention a file.",
    placeholderDrama: "Paste a chapter or ask about this episode…",
    placeholderCanvas: "Describe a spatial shot…",
    placeholderCreative: "Describe a clip…",
    disabled: "Set a workspace in Settings to send…",
    enter: "Enter to send",
    queueHint: "Enter queues behind the running turn",
    planHint: "Read and propose. Writes wait.",
    taskPlanProgress: "{done}/{total}",
    showPlan: "Show plan",
    hidePlan: "Hide plan",
    planPending: "Pending",
    planActive: "In progress",
    planDone: "Done",
    workspaceRequired: "Workspace required",
    agent: "Agent",
    plan: "Plan",
    mode: "Mode",
    agentHint: "Run tools and write.",
    send: "Send",
    queue: "Queue",
    queuedCount: "{n} waiting",
    stop: "Stop",
    steer: "Steer",
    mention: "Insert mention",
    attach: "Attach files",
    clipboard: "Paste clipboard",
    screenshot: "Capture screenshot",
    add: "Add",
    more: "More",
    mentions: "Mentions",
    commands: "Commands",
    message: "Message",
    model: "Model",
    context: "Context",
    ctxSystem: "System",
    ctxTools: "Tools",
    ctxDynamic: "Working",
    ctxChat: "Chat",
    ctxFree: "Free",
    ctxWindow: "Window",
    ctxElided: "Elided",
    ctxProvider: "Provider",
    ctxCache: "Cache",
    ctxCacheUnknown: "Provider did not report",
    mentionFile: "Pin a file (bounded)",
    mentionFolder: "Pin a directory listing",
    mentionSkill: "Inject a skill body",
    mentionHarness: "Inject the active harness summary",
    mentionKindFile: "File",
    mentionKindFolder: "Folder",
    mentionKindSkill: "Skill",
    mentionKindHarness: "Harness",
    mentionEmpty: "No matches",
    mentionType: "Type to search files",
    authMode: "Authorization",
    authDefault: "Default",
    authAutoEdit: "Auto-edit",
    authFull: "Full access",
    authAsk: "Ask every time",
    workspace: "Workspace",
    workspaceHint: "This chat's tools, files, and patches run here.",
    browseWorkspace: "Choose folder…",
    isolate: "Worktree",
    isolateOn: "Isolated checkout",
    isolateOff: "Edit the origin folder",
    isolateHint: "Run tools in a git worktree. Merge stays a Review action.",
  },
  slash: {
    new: "New chat",
    rename: "Rename this chat",
    fork: "Fork this chat",
    archive: "Archive this chat",
    delete: "Delete this chat",
    plan: "Toggle plan mode",
    diff: "Refresh review diff",
    steer: "Steer the running turn",
    compact: "Compact context",
    rewind: "Rewind / summarize from here",
    model: "Set chat model",
    export: "Export as markdown",
    stop: "Stop the running turn",
    quit: "Quit Yoyo",
    schedule: "Create a heartbeat or cron job",
    remember: "Stage a memory item",
    forget: "Forget a memory id",
    project: "Create a personal-OS project",
    artifact: "Ask for a document/spreadsheet/slides pack",
  },
  review: {
    diff: "Diff",
    files: "Files",
    context: "Context",
    ask: "Ask",
    refresh: "Refresh",
    apply: "Apply selected",
    unified: "Unified",
    split: "Split",
    noHunks: "No changes in the workspace yet.",
    noHunksHint: "Edits the agent makes will show up here as hunks you can apply.",
    noFiles: "No changed files yet.",
    changes: "{files} files · {hunks} hunks",
    hunksCount: "{n} hunks",
    hunkOne: "1 hunk",
    applyN: "Apply {n}",
    clear: "Clear",
    selectFile: "Select every hunk in this file",
    approvals: "Approvals",
    inbox: "Inbox",
    drafts: "Drafts",
    browserActions: "Browser",
    nothingWaiting: "Nothing is waiting on you.",
    open: "Open",
    tokens: "Tokens",
    budget: "Budget",
    elided: "Elided",
    contextNote: "Trusted pins survive every turn. Tool transcript is untrusted working memory.",
    noAsk: "No pending approvals. In-stream cards appear in the transcript.",
    toggle: "Toggle review",
    tabs: "Review",
    queue: "Queue",
    noQueue: "Approvals, inbox items, and drafts will collect here.",
    diffLayout: "Diff layout",
    contextMoved: "Token usage sits under the composer.",
    once: "Once",
    session: "Session",
    always: "Always",
    deny: "Deny",
    quote: "Quote into composer",
    openReview: "Open in Review",
    skills: "Skills",
    memory: "Memory",
    pin: "Pin",
    unpin: "Unpin",
    loaded: "Loaded this turn",
    pinned: "Pinned",
    inspect: "Inspect",
    noSkills: "No skills on disk for this workspace.",
    noMemory: "No memories yet.",
    noMemoryHint: "Things the agent learns land in Staging; promote what should survive.",
    staging: "Staging",
    trusted: "Trusted",
    promote: "Promote",
    forget: "Forget",
    dismiss: "Dismiss",
    openThread: "Open thread",
  },
  trace: {
    tab: "Trace",
    refresh: "Refresh",
    empty: "No events yet. Run a turn to record a trajectory.",
    noSession: "Select a chat to inspect its trace.",
    events: "Events",
    tools: "Tools",
    errors: "Errors",
    tokens: "Tokens",
    duration: "Duration",
    spilled: "Spill",
    artifacts: "Artifacts",
    timeline: "Timeline",
    filterAll: "All",
    filterExec: "Calls",
    filterDialog: "Chat",
    filterMemory: "Memory",
    filterError: "Errors",
    copy: "Copy",
    copied: "Copied",
    sessionId: "Session ID",
    copyId: "Copy session ID",
    loadSpill: "Full artifact",
    truncated: "Truncated",
    bytes: "bytes",
    noMatch: "No events in this filter.",
  },
  control: {
    title: "Control",
    hint: "Vault, policy, and updater. The agent cannot change these surfaces.",
    appearance: "Appearance",
    appearanceHint: "Theme follows the window, not the agent.",
    provider: "Provider",
    providerHint: "Keys stay in the vault. The agent cannot read them.",
    workspace: "Workspace",
    workspaceHint: "Turns run against this directory by default. Each chat can override.",
    policy: "Policy",
    policyHint: "Deny-first unless you opt in. Budget is a hard stop.",
    plugins: "Plugins",
    pluginsHint: "WASM stays HighRisk + ForceAsk. No WASI filesystem.",
    colorMode: "Color mode",
    resolved: "Resolved",
    captionFollow: "Caption buttons and window background follow this.",
    model: "Model",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "paste then Save — stored in vault",
    extraModels: "Extra models (BoN)",
    path: "Path",
    autoAllow: "Auto-allow shell (deny-first stays off unless you opt in)",
    maxBudget: "Max budget USD",
    usdPerMtok: "USD per MTok",
    noFibers: "No extra fibers loaded.",
    unload: "Unload",
    save: "Save",
    applyUpdate: "Apply staged update",
    checkUpdate: "Check staged update",
    unsaved: "Unsaved changes",
    system: "System",
    dark: "Dark",
    light: "Light",
    browse: "Browse",
    mcp: "MCP",
    mcpHint: "Stdio servers. Tools stay behind the network gate.",
    mcpName: "Name",
    mcpCommand: "Command",
    mcpArgs: "Args",
    mcpStart: "Start",
    mcpStop: "Stop",
    logs: "Logs",
    logsHint: "Process diagnostics. Secrets and chat bodies are redacted.",
    doctor: "Doctor",
    closeToTray: "Close to tray",
    vaultSource: "Vault",
    noMcp: "No MCP servers running.",
    shortcuts: "Shortcuts",
    shortcutsHint: "Remappable keyboard paths. The agent cannot edit the keymap.",
    language: "Language",
    quitRunning: "A turn is still running. Quit anyway?",
  },
  labs: {
    harbor: "Harbor",
    harborHint: "Held-in must not drop, held-out must not drop, safety fail never promotes.",
    evolve: "Evolve",
    evolveHint: "ACE deltas grow the playbook. Harbor still owns refs/active.",
    harness: "Harness",
    harnessHint: "Only pointers move. Checkout of loop/policy topology needs L3.",
    k: "K",
    rounds: "Rounds",
    sealed: "Sealed 12/8/10",
    runCycle: "Run cycle",
    noCycle: "No cycle yet.",
    promoted: "Canary",
    parent: "Parent",
    trials: "Trials",
    merged: "Merged",
    activeMoved: "Active moved",
    proposal: "Proposal",
    accepted: "Accepted",
    reason: "Reason",
    in: "In",
    out: "Out",
    hit: "Hit",
    miss: "Miss",
    spend: "Spend",
    usd: "USD",
    tokens: "Tokens",
    wall: "Wall",
    behavior: "Behavior probes",
    index: "Index transfer",
    baselines: "BoN / IID / SCS",
    maxUsd: "Max USD",
    goNoGo: "Go only if evolve held-out gain beats BoN and IID on this budget. Otherwise freeze search structure.",
    labCompare: "Matched-budget lab",
    bon: "Best-of-N",
    iid: "IID",
    scs: "SCS",
    playbook: "Playbook",
    archive: "Archive",
    helpful: "Helpful",
    harmful: "Harmful",
    rejected: "rejected",
    rollback: "Rollback",
    notTrusted: "not trusted",
    trusted: "trusted",
    checkout: "Checkout",
    diffAsB: "Diff as B",
    fieldDiff: "Field diff",
    hashFields: "Hash fields",
    hashA: "hash A",
    hashB: "hash B",
    compare: "Compare",
    field: "Field",
    from: "From",
    to: "To",
    l3: "L3 checkout",
    busyHarbor: "Harbor running…",
    busyEvolve: "Evolve running…",
    timeline: "Version timeline",
    thisCycle: "This cycle",
    playbookDelta: "Playbook delta",
    noDelta: "No bullets merged this cycle.",
    moveActive: "Move active here",
    compareStaging: "Compare staging to active",
    ceremony: "Checkout is a human gate. Staging is never trusted.",
    advancedHashes: "Compare any two hashes",
  },
  settings: {
    back: "Back",
    title: "Settings",
    hint: "Vault, policy, and updater. The agent cannot change these surfaces.",
    groups: {
      app: "Application",
      agent: "Agent",
      system: "System",
    },
    tabs: {
      general: "General",
      appearance: "Appearance",
      shortcuts: "Shortcuts",
      provider: "Models",
      generation: "Generation",
      policy: "Safety",
      extensions: "Extensions",
      personal: "Personal",
      advanced: "Advanced",
    },
    tabHints: {
      general: "Where turns run, and how the desktop app behaves.",
      appearance: "Mode, palette, language, and interface size. The agent never changes these.",
      shortcuts: "Remappable keyboard paths. The agent cannot edit the keymap.",
      provider: "Keys stay in the vault. The agent cannot read them.",
      generation: "Image, speech, video, and canvas protocol channels. Keys stay in the vault.",
      policy: "Deny-first unless you opt in. Budget is a hard stop.",
      extensions: "Extra tools and accounts. Everything stays behind the network gate.",
      personal: "What Yoyo remembers, and what it runs on a schedule.",
      advanced: "Updater, diagnostics, and irreversible actions.",
    },
    sections: {
      generalWorkspace: "Workspace",
      generalNotifications: "Notifications",
      generalDesktop: "Desktop",
      appearanceTheme: "Color mode",
      appearancePalette: "Palette",
      appearanceDisplay: "Display",
      shortcutsMap: "Keymap",
      providerAccount: "Connection",
      providerModels: "Catalog",
      providerVideo: "Image, speech & video",
      generationStudio: "Workshop",
      generationCanvas: "Extra canvas channels",
      generationImage: "Image",
      generationVideo: "Video",
      generationSpeech: "Speech",
      generationStyles: "Styles",
      policyGate: "Approvals",
      policyBudget: "Budget",
      policyIsolation: "Runtime",
      extensionsMcp: "MCP servers",
      extensionsFibers: "Plugins",
      extensionsConnectors: "Connected accounts",
      personalMemory: "Memory",
      personalJobs: "Scheduled jobs",
      advancedUpdates: "Updates",
      advancedLogs: "Diagnostics",
      advancedJournal: "Journal",
      advancedDoctor: "Doctor",
      advancedDanger: "Irreversible",
    },
    keys: {
      palette: "Command palette",
      newChat: "New chat",
      control: "Open settings",
      toggleReview: "Toggle review pane",
      once: "Approve once",
      session: "Approve for session",
      always: "Approve always",
      deny: "Reject",
    },
    search: "Search settings…",
    searchEmpty: "No matching setting.",
    discard: "Discard",
    saveChanges: "Save changes",
    editJson: "Edit as JSON",
    addServer: "Add server",
    noConnectors: "No connected accounts.",
    noMemory: "Nothing remembered yet.",
    noJobs: "No scheduled jobs.",
    fibersHint: "WASM stays HighRisk + ForceAsk. No WASI filesystem.",
    memoryPlaceholder: "Something Yoyo should remember about you…",
    workspace: "Workspace",
    workspaceDesc: "Default folder for Agent chats. Each Agent chat can pick its own workspace.",
    videoWorkspace: "Video workspace",
    videoWorkspaceDesc: "Default folder for Video chats. Separate from the Agent workspace.",
    browse: "Browse",
    language: "Language",
    languageDesc: "Interface language. Native menus and the tray follow immediately.",
    closeToTray: "Close to tray",
    closeToTrayDesc: "Hide the window instead of quitting.",
    companion: "Desktop companion",
    companionDesc: "Sits on the desktop beside this window. The tray menu toggles it. It stays off the taskbar and speaks notices as they happen.",
    startAtLogin: "Open at login",
    startAtLoginDesc: "Start Yoyo when you sign in to this computer.",
    alwaysOnTop: "Always on top",
    alwaysOnTopDesc: "Keep the window above other applications.",
    notifications: "System notifications",
    notificationsDesc: "Turn-end, approval, and error toasts from the OS.",
    notifyUnfocused: "Only when unfocused",
    notifyUnfocusedDesc: "Skip OS notifications while this window is focused.",
    uiScale: "Interface scale",
    uiScaleDesc: "Size of UI chrome. Chat density stays the same.",
    colorMode: "Color mode",
    colorModeDesc: "Caption buttons and window chrome follow this.",
    system: "System",
    dark: "Dark",
    light: "Light",
    resolved: "Resolved",
    palettesDesc: "Dark and light palettes are stored separately. Terracotta stays the accent in every room.",
    paletteGroupDark: "Dark",
    paletteGroupLight: "Light",
    palettes: {
      ink: "Ink",
      inkHint: "Warm charcoal. Desk lamp at night.",
      dim: "Dim",
      dimHint: "A little lifted, still warm.",
      slate: "Slate",
      slateHint: "Cooler charcoal. Same ember.",
      neutral: "Neutral",
      neutralHint: "Gallery plaster. Quiet stone.",
      paper: "Paper",
      paperHint: "Warm notebook, still slate-adjacent.",
      mist: "Mist",
      mistHint: "Pearl fog. Almost white.",
    },
    provider: "Provider",
    providerDesc: "OpenAI-compatible chat completions. Pick a preset to fill the base URL and default model.",
    providerPreset: "Presets fill a compatible endpoint. Save still stores the key in the vault.",
    ctxWindow: "Context window",
    outputLimit: "Max output",
    vision: "Vision",
    reasoning: "Reasoning",
    perMillion: "/MTok",
    modelsCount: "models",
    catalogHint: "Lists and context windows come from models.dev. Pick a model to make it the default.",
    selectedModel: "Default model",
    presetHintClaude: "Needs an OpenAI-compatible gateway, or use OpenRouter.",
    presetHintAzure: "Replace YOUR_RESOURCE with the Azure resource name.",
    presetHintCustom: "Any OpenAI-compatible /v1/chat/completions endpoint.",
    yes: "Yes",
    no: "No",
    oauth: "OAuth",
    model: "Model",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "paste then Save — stored in vault",
    extraModels: "Extra models (BoN)",
    vaultSource: "Vault",
    saveProvider: "Save provider",
    testConnection: "Test connection",
    testOk: "Provider reachable",
    testFail: "Provider check failed",
    autoAllow: "Auto-allow shell",
    autoAllowDesc: "Deny-first stays off unless you opt in.",
    gateMode: "Approval mode",
    gateModeDesc: "Manual always asks. AutoSafe runs injection/exfil heuristics then asks on hits. Skip is operator-only and still ForceAsks identity actions.",
    gateManual: "Manual",
    gateAutoSafe: "AutoSafe",
    gateSkip: "Skip",
    crashResume: "Resume crashed turns",
    crashResumeDesc: "Non-identity turns restart after a daemon crash. High-risk grants are never restored.",
    searchUrl: "Search API",
    searchUrlDesc: "HTTPS endpoint or template with {q}. DuckDuckGo scrape is fallback only.",
    isolationHint: "A sandbox badge is shown only when the OS isolator is actually wrapping shell. Job objects are containment, not a sandbox.",
    isolationKind: "Isolator",
    isolationSandbox: "Sandbox",
    isolationSigned: "Signature",
    isolationVault: "Vault",
    isolationBrowser: "Browser profile",
    isolationSleep: "This machine sleeps: scheduled jobs skip. Run yoyo daemon on an always-on node.",
    connectorsHint: "OAuth tokens go in the OS keychain. Send-as-you is always ForceAsk.",
    connect: "Connect",
    memoryHint: "Writes stay on staging until you promote. Forget is immediate.",
    promote: "Promote",
    forget: "Forget",
    automationsHint: "Jobs run in a copied worktree. They never send_as_you without a later approval.",
    scheduleKind: "Kind",
    scheduleSpec: "Spec",
    schedulePrompt: "Prompt",
    addJob: "Add job",
    mcpHttp: "MCP HTTP",
    mcpEndpoint: "Endpoint",
    mcpHttpHint: "Streamable HTTP MCP. Tokens stay in the vault.",
    expertDir: "Expert pack directory",
    expertAdmit: "Admit signed skill",
    expertHint: "Unsigned packs cannot become refs/active.",
    maxBudget: "Max budget USD",
    usdPerMtok: "USD per MTok",
    savePolicy: "Save policy",
    mcpHint: "Stdio servers. Tools stay behind the network gate.",
    mcpName: "Name",
    mcpCommand: "Command",
    mcpArgs: "Args",
    mcpStart: "Start",
    mcpStop: "Stop",
    noMcp: "No MCP servers running.",
    mcpJson: "MCP JSON",
    mcpJsonDesc: "Array of {name, command, args}. Replaces the running set.",
    applyJson: "Apply JSON",
    noFibers: "No extra fibers loaded.",
    unload: "Unload",
    unloadConfirm: "Unload this fiber? WASM stays HighRisk + ForceAsk.",
    recordHint: "Click a binding, then press the new shortcut.",
    recording: "Press keys…",
    currentVersion: "Current version",
    channel: "Channel",
    updateUrl: "Update URL",
    updateUrlDesc: "Signed manifest. Staging is never trusted until you apply.",
    checkUpdate: "Check for update",
    applyUpdate: "Apply staged update",
    applyUpdateConfirm: "Apply the staged binary? This rewrites the running app. The agent cannot do this.",
    noStaged: "No staged update",
    logsHint: "Process diagnostic tail. Secrets and chat bodies stay off disk.",
    journalHint: "Hash-chain audit. The agent cannot edit this file.",
    follow: "Follow",
    reveal: "Show in folder",
    copyPath: "Copy path",
    filterLevel: "Level",
    exportBundle: "Export support bundle",
    diagnoseTurn: "Diagnose this turn",
    emptyLogs: "No diagnostic records yet.",
    emptyJournal: "No journal records yet.",
    pathCopied: "Path copied",
    exportedBundle: "Support bundle written",
    crashFile: "Crash file",
    doctor: "Doctor",
    checkoutConfirm: "Checkout moves harness pointers. Loop/policy topology needs L3 confirmation. Staging is not trusted.",
    checkout: "Checkout requires a hash in Harness.",
    save: "Save",
    unsaved: "Unsaved changes",
    english: "English",
    chinese: "中文",
  },
    rsi: {
    title: "Harness",
    hint: "Propose, prove, then move pointers. Staging is never trusted.",
    overview: "Overview",
    propose: "Propose",
    prove: "Prove",
    promote: "Promote",
    overviewHint: "Where the pointers sit, and what to do next",
    proposeHint: "ACE thumbs write staging; evolve writes canary",
    proveHint: "Harbor must not regress held-in or held-out",
    promoteHint: "Checkout moves pointers. Loop/policy topology needs L3",
    next: "Next",
    nextEvolve: "No candidate on staging or canary. Run an evolve cycle.",
    nextEval: "Staging differs from active. Run the suite before checkout.",
    nextCanaryEval: "Canary differs from active. Run Harbor before checkout.",
    nextCheckout: "Harbor evidence is clean. Checkout staging onto active.",
    nextCanaryCheckout: "Harbor evidence is clean. Checkout canary onto active.",
    nextBlocked: "Safety fail — Harbor will not promote.",
    nextIdle: "Active is trusted. Evolve when you want a candidate.",
    moreEvals: "More evals",
    danger: "Danger",
    copyHash: "Copy hash",
    copied: "Copied",
    active: "active",
    staging: "staging",
    canary: "canary",
    canaryDirty: "canary",
    head: "HEAD",
    lastEval: "Last Harbor run",
    noRefs: "No harness refs yet. Run init, then refresh.",
    go: "Go",
    lineage: "Evolution path",
    lineageHint: "Each snapshot lists what changed versus its parent. Pointers are labels on the same objects.",
    seed: "seed",
    noLineage: "No snapshots reachable from refs yet. Run init, then refresh.",
    openStore: "Show store",
    openArtifacts: "Show artifacts",
    vsParent: "vs parent",
    noChanges: "No material changes versus parent.",
    added: "added",
    removed: "removed",
    changed: "changed",
    l3: "L3",
    revealFailed: "Could not open the harness folder.",
  },
  about: {
    title: "About Yoyo",
    body: "One Go loop. Harbor before promote. Vault and updater stay off-agent.",
    close: "Close",
  },
  harbor: {
    empty: "Smoke suite: held-in write-hello, held-out write-answer, safety no-escape. Sealed 12/8/10 is opt-in.",
    noResults: "Run finished with no task rows.",
    retry: "Retry",
    heldIn: "Held-in",
    heldOut: "Held-out",
    safety: "Safety fail",
    runSuite: "Run suite",
    runSafety: "Suite + safety",
    runTb: "TB subset",
    runBon: "Best-of-3",
    runModels: "Models BoN",
    runSealed: "Sealed 12/8/10",
    runTransfer: "Transfer",
    runIndex: "Index transfer",
    runBehavior: "Behavior probes",
    modelsPh: "models a,b",
    whySafety: "Safety suite failed — Harbor will not promote.",
    whyEvidence: "This run is evidence. Promotion still requires a candidate vs baseline non-regression gate.",
    task: "Task",
    kind: "Kind",
    pass: "Pass",
    fail: "Fail",
    error: "Error",
    runN: "Run",
    storyHeldIn: "Does it still do what we trained?",
    storyHeldOut: "Does it transfer?",
    storySafety: "Safety veto",
    verdict: "Verdict",
    verdictPromote: "Evidence allows a promotion conversation.",
    verdictBlock: "Blocked. Do not checkout.",
    verdictIdle: "Run the suite before moving pointers.",
  },
  skills: {
    title: "Skills",
    hint: "Installed packs are available in chat with @skill. Market installs the full folder — SKILL.md plus scripts, references, and assets — into ~/.yoyo/skills.",
    installed: "Installed",
    market: "Market",
    search: "Search catalog…",
    emptyInstalled: "No skill packs on disk yet.",
    emptyMarket: "Catalog unavailable. Check the network, then refresh.",
    refresh: "Refresh catalog",
    install: "Install",
    installing: "Installing…",
    installedBadge: "Installed",
    uninstall: "Remove",
    pinThread: "Pin to chat",
    unpinThread: "Unpin",
    inspect: "Inspect",
    bundled: "Bundled",
    home: "Home",
    workspace: "Workspace",
    marketSource: "Market",
    cas: "Harness",
    needsShell: "Asks for shell tools. The capability gate still applies.",
    scanOk: "Scan passed",
    attribution: "Work Buddy public catalog (infometa/workbuddyskills). Source files only — Yoyo does not run zip executables on install.",
    count: "{n}",
    featured: "Featured",
    all: "All",
    close: "Back to chat",
    noThread: "Open a chat to pin a skill.",
    loaded: "Loaded this turn",
    none: "None",
    repair: "Repair pack",
    repairing: "Repairing…",
    incomplete: "Missing scripts",
    hasScripts: "Scripts",
    files: "{n} files",
    installPartial: "SKILL.md installed, but helper scripts were not fetched. Repair the pack.",
    repaired: "Pack repaired",
  },
  palette: {
    title: "Command palette",
    desc: "Jump to a thread, lab, setting, or action",
    placeholder: "Jump to a thread or action…",
    empty: "No matches",
    actions: "Actions",
    rsi: "RSI",
    chats: "Chats",
    settings: "Settings",
    newChat: "New chat",
    agent: "Agent",
    openHarness: "Open Harness",
    openSkills: "Open Skills",
    openVideo: "Open Video",
    videoGroup: "Video",
    videoCreate: "Create",
    videoDrama: "Drama",
    videoCanvas: "Infinite canvas",
    videoAssets: "Assets",
    videoPlugins: "Plugins",
    videoTasks: "Creation history",
    refreshDiff: "Refresh diff",
    about: "About",
    quit: "Quit",
    runSuite: "Run eval suite",
    runCycle: "Run evolve cycle",
  },
  titlebar: {
    fork: "Fork",
    diff: "Diff",
    live: "live",
    waiting: "waiting",
    lastTool: "last tool",
    rename: "Rename chat",
    inbox: "Inbox",
    copyId: "Copy session ID",
    copiedId: "Copied session ID",
  },
  dock: {
    chat: "Chat",
    expand: "Expand",
    toggle: "Toggle chat",
  },
  video: {
    title: "Video",
    close: "Back",
    modes: "Modes",
    drama: "Drama agent",
    dramaHint: "Novel to episode: script, stills, shots, stitch.",
    canvas: "Infinite canvas",
    canvasHint: "Spatial generation workspace: nodes, tools, timeline, director.",
    canvasMcp: "Expose MCP on canvas threads",
    canvasMcpHint: "Off by default. Canvas sessions hide global MCP tools unless you turn this on.",
    creative: "Creative",
    creativeHint: "Single-clip play. Same adapters, later.",
    later: "Creative mode is not wired yet. Short drama and infinite canvas share this substrate.",
    soon: "later",
    workshop: "Workshop",
    workshopHint: "Episode board, stills, and cut.",
    noProject: "No episode",
    noCanvas: "No board",
    openBoard: "Episode board",
    openCanvas: "Open canvas",
    closeBoard: "Back to chat",
    shell: "Workspace",
    shellLibrary: "Library",
    shellCreate: "Create",
    shellDrama: "Drama",
    shellCanvas: "Canvas",
    shellAssets: "Assets",
    shellSkills: "Skills",
    shellPlugins: "Plugins",
    shellTasks: "Creation history",
    historyHint: "Short dramas, canvases, and generation jobs live here.",
    historyProjects: "Projects",
    historyJobs: "Jobs",
    historyEmptyCanvas: "Boards you create will show up here.",
    newCanvas: "New board",
    pickSeries: "Series",
    pickEpisode: "Episode",
    newDrama: "New series",
    newEpisode: "New episode",
    untitled: "Untitled series",
    untitledEp: "Untitled episode",
    import: "Import Huobao project",
    importHint: "Copies dramas without API keys.",
    empty: "No series yet",
    emptyHint: "Start with a title and a chapter of prose. The pipeline does the rest.",
    script: "Script",
    cast: "Cast",
    board: "Board",
    cut: "Cut",
    novel: "Source",
    screenplay: "Screenplay",
    rewrite: "Rewrite",
    extract: "Extract",
    prompts: "Prompts",
    stills: "Stills",
    storyboard: "Board",
    vprompts: "Shot prompts",
    clips: "Clips",
    stitch: "Stitch",
    duration: "Duration plan",
    chars: "chars",
    seconds: "s",
    segments: "segments",
    generate: "Generate",
    generateAll: "Generate missing",
    retry: "Retry",
    cancel: "Cancel",
    upload: "Upload still",
    bindChat: "Bind this episode to chat",
    language: "Content language",
    style: "Style",
    ratio: "Frame",
    resolution: "Resolution",
    providers: "Providers",
    imageProvider: "Image",
    videoProvider: "Video",
    missingKey: "Add a vault key in Settings → Generation.",
    ffmpegMissing: "Install ffmpeg or set FFMPEG_BIN to stitch clips.",
    noStills: "No still yet",
    noClip: "No clip yet",
    characters: "Characters",
    scenes: "Scenes",
    props: "Props",
    mention: "Mention an asset",
    jobs: "Jobs",
    queued: "queued",
    running: "running",
    polling: "polling",
    succeeded: "done",
    failed: "failed",
    selected: "Selected clips",
    export: "Stitch selected",
    play: "Play",
    next: "Next",
    save: "Save",
    delete: "Delete",
    locked: "Frame locked for the series",
    dockHint: "Chat stays on this episode’s drama tools.",
    stageBusy: "Stage running…",
    needSession: "Open a chat first so the stage can bind a thread.",
    needPrompt: "Write a video prompt or attach stills first.",
    needClips: "Generate clips before stitching.",
    ffmpeg: "FFmpeg",
    apiKey: "API key",
    episodes: "Episodes",
    bound: "Bound to chat",
    confirmDelete: "Confirm delete",
    selectAll: "All clips with video",
    selectNone: "None",
    clipCount: "clips",
    skipRewrite: "Use source as script",
    extractChars: "Characters only",
    extractScenes: "Scenes only",
    extractProps: "Props only",
    addCharacter: "Add character",
    addScene: "Add scene",
    addProp: "Add prop",
    appearance: "Look",
    styling: "Costume",
    lighting: "Light",
    finalPrompt: "Still prompt",
    bindRefs: "Shot references",
    history: "Takes",
    setMain: "Use this take",
    download: "Download",
    narrator: "Narrator — no still",
    durationLabel: "Seconds",
    editAsset: "Edit",
    noHistory: "No takes yet",
    kindImage: "Image",
    kindVideo: "Video",
    kindSpeech: "Speech",
    customProvider: "Custom adapter",
    makeDefault: "Default",
    enabled: "On",
    missingProviders: "Add image and video keys in Settings → Generation before generating.",
    openSettings: "Open settings",
    adapterName: "Name",
    modelsCsv: "Model catalog",
    noAdapter: "No adapter yet. Pick a vendor template, then paste the vault key.",
    providerHint: "Each row is a generation adapter. Keys stay in the vault.",
    multiAdapterHint: "Add as many adapters as you need — including several of the same vendor. Each row keeps its own key and catalog. Drama, Create, and Canvas all read this list.",
    canvasChannelsHint: "Studio adapters above already feed Create and Canvas. Add a row here only for a Yingce plugin that is not in those lists.",
    canvasChannelsEmpty: "No extra channels. Image, video, and speech adapters above already feed Create and Canvas.",
    defaultModel: "Default model",
    styleHint: "Style prefixes still prompts. Hidden presets stay out of the series picker.",
    styleName: "Style name",
    addStyle: "Add style",
    unbind: "None",
    keySaved: "Key saved",
    noKey: "No key",
    addAdapter: "Add adapter",
    deleteAdapter: "Remove this adapter and its vault key?",
    vendor: "Vendor",
    ffmpegReady: "Ready",
    langZh: "Chinese",
    langEn: "English",
    langOther: "Other",
    speechHint: "Speech adapters are stored for later voice work. Drama clips use the video model's native audio.",
    hideStyle: "Hide",
    restoreStyle: "Restore",
    styleValue: "Key",
    templateHint: "Start from a vendor template, then paste the key.",
    styleHidden: "Hidden",
    setDefault: "Set default",
  },
  window: {
    minimise: "Minimise",
    maximise: "Maximise",
    close: "Close",
  },
} as const;

export type Copy = typeof en;

let active: Copy = en;

export function setCopyCatalog(next: Copy) {
  active = next;
}

export function catalog(): Copy {
  return active;
}

export const copy: Copy = new Proxy({} as Copy, {
  get(_target, prop) {
    return (active as Record<PropertyKey, unknown>)[prop];
  },
});
