/** English copy. Keys are stable so zh-CN can land without hunting strings. */
export const en = {
  app: {
    setupBanner: "Set a workspace and API key before the first turn.",
    openControl: "Open Settings",
    dismiss: "Dismiss",
    retry: "Retry",
    applied: "Applied selected hunks",
    undone: "Reverted selected hunks",
    undo: "Undo",
    controlSaved: "Settings saved",
    checkedOut: "Checked out",
    rolledBack: "Rolled back",
    stagedUpdate: "Staged update applied",
    setupFirst: "Set a workspace in Settings first.",
    queued: "Queued for the next turn",
    steered: "Steering injected",
    compacted: "Context compacted",
    deleted: "Thread deleted",
    archived: "Archived",
    unarchived: "Unarchived",
    pinned: "Pinned",
    unpinned: "Unpinned",
    forked: "Forked",
    exported: "Copied export",
    about: "About",
    quit: "Quit",
    turnFinished: "Turn finished",
    approval: "Approval",
    errorNotice: "Error",
  },
  dialog: {
    cancel: "Cancel",
    confirm: "Confirm",
  },
  rail: {
    newChat: "New chat",
    search: "Search chats",
    noChats: "No chats yet",
    running: "Running",
    idle: "Idle",
    archived: "Archived",
    pin: "Pin",
    unpin: "Unpin",
    archive: "Archive",
    unarchive: "Unarchive",
    rename: "Rename",
    fork: "Fork",
    delete: "Delete",
    showArchived: "Show archived",
    hideArchived: "Hide archived",
    jump: "Jump",
    more: "Chat actions",
    untitled: "Untitled chat",
    connected: "Connected",
    disconnected: "Disconnected",
    isolated: "isolated",
    chats: "Chats",
    labs: "Labs",
    settings: "Settings",
    control: "Settings",
    collapse: "Collapse sidebar",
    expand: "Expand sidebar",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    clearNotifications: "Clear",
    harbor: "Harbor",
    harborHint: "Eval before promote",
    evolve: "Evolve",
    evolveHint: "ACE / DGM cycle",
    harness: "Harness",
    harnessHint: "Refs and checkout",
  },
  transcript: {
    ready: "Ready for a turn",
    readyBody: "Pin extra context with @file:path, @folder:dir, or @harness. Plan mode proposes without writing.",
    setupTitle: "Set a workspace first",
    setupBody: "Pick a folder and API key in Settings before the first turn.",
    openControl: "Open Settings to set workspace",
    working: "Working…",
    needsApproval: "Needs approval",
    mention: "Mention",
    thinking: "Reasoning",
    plan: "Plan",
    subagent: "Subagent",
    patch: "Patch",
    copy: "Copy",
    once: "Once",
    session: "Session",
    always: "Always",
    deny: "Deny",
    starters: [
      { label: "Summarize the workspace", text: "Summarize this workspace and list the files that matter." },
      { label: "Pin the harness", text: "@harness\nWhat is the active harness and what can I safely change?" },
      { label: "Plan a change", text: "Propose a plan to add a README section describing how to run Yoyo desktop." },
    ],
  },
  composer: {
    placeholder: "Message Yoyo",
    disabled: "Set a workspace in Settings to send…",
    enter: "Enter to send",
    queueHint: "Enter queues behind the running turn",
    planHint: "Read and propose. Writes wait.",
    workspaceRequired: "Workspace required",
    agent: "Agent",
    plan: "Plan",
    send: "Send",
    queue: "Queue",
    stop: "Stop",
    steer: "Steer",
    mention: "Insert mention",
    attach: "Attach files",
    mentions: "Mentions",
    commands: "Commands",
    message: "Message",
    model: "Model",
    context: "Context",
    mentionFile: "Pin a file (bounded)",
    mentionFolder: "Pin a directory listing",
    mentionSkill: "Inject a skill body",
    mentionHarness: "Inject the active harness summary",
  },
  slash: {
    new: "New chat",
    rename: "Rename this chat",
    fork: "Fork this chat",
    archive: "Archive this chat",
    delete: "Delete this chat",
    plan: "Toggle plan mode",
    diff: "Refresh review diff",
    steer: "Steer the running turn",
    compact: "Compact context",
    model: "Set chat model",
    export: "Export as markdown",
    stop: "Stop the running turn",
    quit: "Quit Yoyo",
  },
  review: {
    diff: "Diff",
    files: "Files",
    context: "Context",
    ask: "Ask",
    refresh: "Refresh",
    apply: "Apply selected",
    unified: "Unified",
    split: "Split",
    noHunks: "No hunks. Run a turn, then refresh.",
    noFiles: "No changed files in the current diff.",
    tokens: "Tokens",
    budget: "Budget",
    elided: "Elided",
    contextNote: "Trusted pins survive every turn. Tool transcript is untrusted working memory.",
    noAsk: "No pending approvals. In-stream cards appear in the transcript.",
    toggle: "Toggle review",
    tabs: "Review",
    diffLayout: "Diff layout",
    contextMoved: "Token usage sits under the composer.",
    once: "Once",
    session: "Session",
    always: "Always",
    deny: "Deny",
    quote: "Quote into composer",
    openReview: "Open in Review",
  },
  control: {
    title: "Control",
    hint: "Vault, policy, and updater. The agent cannot change these surfaces.",
    appearance: "Appearance",
    appearanceHint: "Theme follows the window, not the agent.",
    provider: "Provider",
    providerHint: "Keys stay in the vault. The agent cannot read them.",
    workspace: "Workspace",
    workspaceHint: "Turns run against this directory.",
    policy: "Policy",
    policyHint: "Deny-first unless you opt in. Budget is a hard stop.",
    plugins: "Plugins",
    pluginsHint: "WASM stays HighRisk + ForceAsk. No WASI filesystem.",
    colorMode: "Color mode",
    resolved: "Resolved",
    captionFollow: "Caption buttons and window background follow this.",
    model: "Model",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "paste then Save — stored in vault",
    extraModels: "Extra models (BoN)",
    path: "Path",
    autoAllow: "Auto-allow shell (deny-first stays off unless you opt in)",
    maxBudget: "Max budget USD",
    usdPerMtok: "USD per MTok",
    noFibers: "No extra fibers loaded.",
    unload: "Unload",
    save: "Save",
    applyUpdate: "Apply staged update",
    checkUpdate: "Check staged update",
    unsaved: "Unsaved changes",
    system: "System",
    dark: "Dark",
    light: "Light",
    browse: "Browse",
    mcp: "MCP",
    mcpHint: "Stdio servers. Tools stay behind the network gate.",
    mcpName: "Name",
    mcpCommand: "Command",
    mcpArgs: "Args",
    mcpStart: "Start",
    mcpStop: "Stop",
    logs: "Logs",
    logsHint: "Journal tail. The agent cannot edit this file.",
    doctor: "Doctor",
    closeToTray: "Close to tray",
    vaultSource: "Vault",
    noMcp: "No MCP servers running.",
    shortcuts: "Shortcuts",
    shortcutsHint: "Remappable keyboard paths. The agent cannot edit the keymap.",
    language: "Language",
    quitRunning: "A turn is still running. Quit anyway?",
  },
  labs: {
    harbor: "Harbor",
    harborHint: "Held-in must not drop, held-out must not drop, safety fail never promotes.",
    evolve: "Evolve",
    evolveHint: "ACE deltas grow the playbook. Harbor still owns refs/active.",
    harness: "Harness",
    harnessHint: "Only pointers move. Checkout of loop/policy topology needs L3.",
    k: "K",
    runCycle: "Run cycle",
    noCycle: "No cycle yet.",
    promoted: "Promoted",
    parent: "Parent",
    trials: "Trials",
    proposal: "Proposal",
    accepted: "Accepted",
    reason: "Reason",
    in: "In",
    out: "Out",
    playbook: "Playbook",
    archive: "Archive",
    helpful: "Helpful",
    harmful: "Harmful",
    rejected: "rejected",
    rollback: "Rollback",
    notTrusted: "not trusted",
    trusted: "trusted",
    checkout: "Checkout",
    diffAsB: "Diff as B",
    fieldDiff: "Field diff",
    hashA: "hash A",
    hashB: "hash B",
    compare: "Compare",
    field: "Field",
    from: "From",
    to: "To",
    l3: "L3 checkout",
    busyHarbor: "Harbor running…",
    busyEvolve: "Evolve running…",
  },
  settings: {
    back: "Back",
    title: "Settings",
    hint: "Vault, policy, and updater. The agent cannot change these surfaces.",
    tabs: {
      general: "General",
      appearance: "Appearance",
      provider: "Provider",
      policy: "Policy",
      mcp: "MCP",
      plugins: "Plugins",
      shortcuts: "Shortcuts",
      updates: "Updates",
      logs: "Logs",
      danger: "Danger zone",
    },
    sections: {
      generalBasics: "Basics",
      generalApp: "App",
      generalDesktop: "Desktop",
      appearanceMode: "Color mode",
      appearanceLanguage: "Language",
      providerAccount: "Account",
      providerModels: "Models",
      policyGate: "Gate",
      policyBudget: "Budget",
      mcpServers: "Servers",
      mcpJson: "Edit JSON",
      pluginsFibers: "Fibers",
      shortcutsMap: "Keymap",
      updatesChannel: "Updates",
      logsJournal: "Journal",
      logsDoctor: "Doctor",
      dangerZone: "Irreversible",
    },
    workspace: "Workspace",
    workspaceDesc: "Turns run against this directory.",
    browse: "Browse",
    language: "Language",
    languageDesc: "Interface language. Native menus and the tray follow immediately.",
    closeToTray: "Close to tray",
    closeToTrayDesc: "Hide the window instead of quitting.",
    startAtLogin: "Open at login",
    startAtLoginDesc: "Start Yoyo when you sign in to this computer.",
    alwaysOnTop: "Always on top",
    alwaysOnTopDesc: "Keep the window above other applications.",
    notifications: "System notifications",
    notificationsDesc: "Turn-end, approval, and error toasts from the OS.",
    notifyUnfocused: "Only when unfocused",
    notifyUnfocusedDesc: "Skip OS notifications while this window is focused.",
    uiScale: "Interface scale",
    uiScaleDesc: "Size of UI chrome. Chat density stays the same.",
    colorMode: "Color mode",
    colorModeDesc: "Caption buttons and window background follow this.",
    system: "System",
    dark: "Dark",
    light: "Light",
    resolved: "Resolved",
    provider: "Provider",
    providerDesc: "OpenAI-compatible chat completions. Pick a preset to fill the base URL and default model.",
    providerPreset: "Presets fill a compatible endpoint. Save still stores the key in the vault.",
    ctxWindow: "Context window",
    outputLimit: "Max output",
    vision: "Vision",
    reasoning: "Reasoning",
    perMillion: "/MTok",
    modelsCount: "models",
    catalogHint: "Lists and context windows come from models.dev. Pick a model to make it the default.",
    selectedModel: "Default model",
    presetHintClaude: "Needs an OpenAI-compatible gateway, or use OpenRouter.",
    presetHintAzure: "Replace YOUR_RESOURCE with the Azure resource name.",
    presetHintCustom: "Any OpenAI-compatible /v1/chat/completions endpoint.",
    yes: "Yes",
    model: "Model",
    baseUrl: "Base URL",
    apiKey: "API key",
    apiKeyPh: "paste then Save — stored in vault",
    extraModels: "Extra models (BoN)",
    vaultSource: "Vault",
    saveProvider: "Save provider",
    testConnection: "Test connection",
    testOk: "Provider reachable",
    testFail: "Provider check failed",
    autoAllow: "Auto-allow shell",
    autoAllowDesc: "Deny-first stays off unless you opt in.",
    maxBudget: "Max budget USD",
    usdPerMtok: "USD per MTok",
    savePolicy: "Save policy",
    mcpHint: "Stdio servers. Tools stay behind the network gate.",
    mcpName: "Name",
    mcpCommand: "Command",
    mcpArgs: "Args",
    mcpStart: "Start",
    mcpStop: "Stop",
    noMcp: "No MCP servers running.",
    mcpJson: "MCP JSON",
    mcpJsonDesc: "Array of {name, command, args}. Replaces the running set.",
    applyJson: "Apply JSON",
    noFibers: "No extra fibers loaded.",
    unload: "Unload",
    unloadConfirm: "Unload this fiber? WASM stays HighRisk + ForceAsk.",
    recordHint: "Click a binding, then press the new shortcut.",
    recording: "Press keys…",
    currentVersion: "Current version",
    channel: "Channel",
    updateUrl: "Update URL",
    updateUrlDesc: "Signed manifest. Staging is never trusted until you apply.",
    checkUpdate: "Check for update",
    applyUpdate: "Apply staged update",
    applyUpdateConfirm: "Apply the staged binary? This rewrites the running app. The agent cannot do this.",
    noStaged: "No staged update",
    logsHint: "Journal tail. The agent cannot edit this file.",
    follow: "Follow",
    reveal: "Show in folder",
    emptyLogs: "No journal records yet.",
    doctor: "Doctor",
    checkoutConfirm: "Checkout moves harness pointers. Loop/policy topology needs L3 confirmation. Staging is not trusted.",
    checkout: "Checkout requires a hash in Harness.",
    save: "Save",
    unsaved: "Unsaved changes",
    english: "English",
    chinese: "中文",
  },
  firstRun: {
    title: "Set up this workstation",
    body: "A workspace is required before a turn. Key and model can wait, but sending stays disabled until the path is saved.",
    stepWorkspace: "Workspace",
    stepKey: "API key",
    stepModel: "Model",
    workspaceHelp: "Absolute path the harness will read and write.",
    keyHelp: "Stored in the vault. The agent cannot read it. Leave blank to paste later in Settings.",
    modelHelp: "Provider model id. Extra BoN models live in Settings.",
    next: "Next",
    back: "Back",
    finish: "Save and continue",
    skip: "Skip for now",
    browse: "Browse",
  },
  about: {
    title: "About Yoyo",
    body: "One Go loop. Harbor before promote. Vault and updater stay off-agent.",
    close: "Close",
  },
  harbor: {
    empty: "Sealed local suite: held-in write-hello, held-out write-answer. TB subset is opt-in.",
    noResults: "Run finished with no task rows.",
    retry: "Retry",
    heldIn: "Held-in",
    heldOut: "Held-out",
    safety: "Safety fail",
    runSuite: "Run suite",
    runSafety: "Suite + safety",
    runTb: "TB subset",
    runBon: "Best-of-3",
    runModels: "Models BoN",
    modelsPh: "models a,b",
    whySafety: "Safety suite failed — Harbor will not promote.",
    whyEvidence: "This run is evidence. Promotion still requires a candidate vs baseline non-regression gate.",
    task: "Task",
    pass: "Pass",
    fail: "Fail",
    error: "Error",
    runN: "Run",
  },
  palette: {
    title: "Command palette",
    desc: "Jump to a thread, lab, setting, or action",
    placeholder: "Jump to a thread or action…",
    empty: "No matches",
    actions: "Actions",
    chats: "Chats",
    settings: "Settings",
    newChat: "New chat",
    agent: "Agent",
    refreshDiff: "Refresh diff",
    about: "About",
    quit: "Quit",
  },
  titlebar: {
    fork: "Fork",
    diff: "Diff",
    live: "live",
    rename: "Rename chat",
  },
  dock: {
    chat: "Chat",
    expand: "Expand",
  },
  window: {
    minimise: "Minimise",
    maximise: "Maximise",
    close: "Close",
  },
} as const;

export type Copy = typeof en;

let active: Copy = en;

export function setCopyCatalog(next: Copy) {
  active = next;
}

export function catalog(): Copy {
  return active;
}

export const copy: Copy = new Proxy({} as Copy, {
  get(_target, prop) {
    return (active as Record<PropertyKey, unknown>)[prop];
  },
});
